use std::collections::HashMap;

use crate::ast::{
    BinaryOp, Block, BlockItem, Expr, Function, MatchArm, Pattern, PrimType, Program, TopLevelItem,
    Type,
};
use crate::error::{Error, Result};
use crate::external::{format_external_path, ExternalFunction};
use crate::platform::{BackendKind, PlatformSpec, Target};
use crate::typecheck::TypedProgram;

trait NativeBackend {
    fn comment_marker(&self) -> &'static str;
    fn main_symbol(&self) -> &'static str;
    fn symbol_name(&self, name: &str) -> String;
    fn external_symbol_name(&self, name: &str) -> String;
    fn stack_note(&self) -> Option<&'static str> {
        None
    }
}

struct Aarch64DarwinBackend;
struct X86_64LinuxGnuBackend;

impl NativeBackend for Aarch64DarwinBackend {
    fn comment_marker(&self) -> &'static str {
        "//"
    }

    fn main_symbol(&self) -> &'static str {
        "_main"
    }

    fn symbol_name(&self, name: &str) -> String {
        format!("_{}", base_symbol_name(name))
    }

    fn external_symbol_name(&self, name: &str) -> String {
        format!("_{name}")
    }
}

impl NativeBackend for X86_64LinuxGnuBackend {
    fn comment_marker(&self) -> &'static str {
        "#"
    }

    fn main_symbol(&self) -> &'static str {
        "main"
    }

    fn symbol_name(&self, name: &str) -> String {
        base_symbol_name(name)
    }

    fn external_symbol_name(&self, name: &str) -> String {
        name.to_string()
    }

    fn stack_note(&self) -> Option<&'static str> {
        Some(".section .note.GNU-stack,\"\",@progbits\n")
    }
}

static AARCH64_DARWIN_BACKEND: Aarch64DarwinBackend = Aarch64DarwinBackend;
static X86_64_LINUX_GNU_BACKEND: X86_64LinuxGnuBackend = X86_64LinuxGnuBackend;

pub(crate) fn emit_assembly_for_platform(
    target: Target,
    platform: &PlatformSpec,
    program: &Program,
    typed: &TypedProgram,
) -> Result<String> {
    if !target.supports_native_backend() {
        return Err(Error::new(format!(
            "target `{target}` does not have a native assembly backend yet"
        )));
    }
    let backend = native_backend(target)?;

    let types_by_name = typed
        .functions
        .iter()
        .map(|function| (function.name.as_str(), function))
        .collect::<HashMap<_, _>>();
    let comment = backend.comment_marker();
    let mut out = String::new();
    out.push_str(comment);
    out.push_str(" Generated by the Emela compiler.\n");
    out.push_str(".text\n\n");

    for function in program.functions() {
        let typed_function = types_by_name[function.name.as_str()];
        if typed_function.effectful || !typed_function.capabilities.is_empty() {
            out.push_str(comment);
            out.push_str(" effects:");
            if typed_function.effectful {
                out.push_str(" effectful");
            }
            if !typed_function.capabilities.is_empty() {
                out.push_str(" requires ");
                out.push_str(
                    &typed_function
                        .capabilities
                        .iter()
                        .map(|capability| format!("{capability:?}"))
                        .collect::<Vec<_>>()
                        .join(","),
                );
            }
            out.push('\n');
        }
        out.push_str(&format!(
            "{comment} signature: ({}) -> {:?}\n",
            typed_function
                .params
                .iter()
                .map(|param| format!("{param:?}"))
                .collect::<Vec<_>>()
                .join(","),
            typed_function.ret
        ));

        let mut emitter = FunctionEmitter::new(target, backend, platform, function, program);
        emitter.emit_function(&mut out)?;
    }

    if let Some(note) = backend.stack_note() {
        out.push_str(note);
    }

    Ok(out)
}

pub(crate) fn emit_js(
    platform: &PlatformSpec,
    program: &Program,
    _typed: &TypedProgram,
) -> Result<String> {
    let mut emitter = JsEmitter::new(platform, program, true);
    emitter.emit_program()
}

pub(crate) fn emit_js_library(
    platform: &PlatformSpec,
    program: &Program,
    _typed: &TypedProgram,
) -> Result<String> {
    let mut emitter = JsEmitter::new(platform, program, false);
    emitter.emit_program()
}

struct FunctionEmitter<'a> {
    target: Target,
    backend: &'static dyn NativeBackend,
    platform: &'a PlatformSpec,
    function: &'a Function,
    program: &'a Program,
    label_prefix: String,
    locals: HashMap<String, i32>,
    next_label: usize,
}

impl<'a> FunctionEmitter<'a> {
    fn new(
        target: Target,
        backend: &'static dyn NativeBackend,
        platform: &'a PlatformSpec,
        function: &'a Function,
        program: &'a Program,
    ) -> Self {
        let mut locals = HashMap::new();
        let mut next_slot = 1;
        for param in &function.params {
            locals.insert(param.name.clone(), -8 * next_slot);
            next_slot += 1;
        }
        collect_block_bindings(&function.body, &mut locals, &mut next_slot);
        Self {
            target,
            backend,
            platform,
            function,
            program,
            label_prefix: sanitize_label(&backend.symbol_name(&function.name)),
            locals,
            next_label: 0,
        }
    }

    fn emit_function(&mut self, out: &mut String) -> Result<()> {
        let symbol = if self.function.name == "main" || self.function.name == "main!" {
            self.backend.main_symbol().to_string()
        } else {
            self.backend.symbol_name(&self.function.name)
        };
        let frame_size = align_to(self.locals.len() as i32 * 8, 16);

        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str(".p2align 2\n");
                out.push_str(&format!(".globl {symbol}\n"));
                out.push_str(&format!("{symbol}:\n"));
                out.push_str("    stp x29, x30, [sp, #-16]!\n");
                out.push_str("    mov x29, sp\n");
                if frame_size > 0 {
                    out.push_str(&format!("    sub sp, sp, #{frame_size}\n"));
                }
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str(".p2align 4\n");
                out.push_str(&format!(".globl {symbol}\n"));
                out.push_str(&format!("{symbol}:\n"));
                out.push_str("    pushq %rbp\n");
                out.push_str("    movq %rsp, %rbp\n");
                if frame_size > 0 {
                    out.push_str(&format!("    subq ${frame_size}, %rsp\n"));
                }
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }

        for (index, param) in self.function.params.iter().enumerate() {
            if index >= 8 {
                return Err(Error::new(
                    "native backend supports at most 8 function parameters",
                ));
            }
            let offset = self.local_offset(&param.name)?;
            match self.target {
                Target::Aarch64AppleDarwin => {
                    out.push_str(&format!("    str x{index}, [x29, #{offset}]\n"));
                }
                Target::X86_64UnknownLinuxGnu => {
                    const ARG_REGS: [&str; 6] = ["%rdi", "%rsi", "%rdx", "%rcx", "%r8", "%r9"];
                    if let Some(reg) = ARG_REGS.get(index) {
                        out.push_str(&format!("    movq {reg}, {offset}(%rbp)\n"));
                    } else {
                        let stack_offset = 16 + (index - ARG_REGS.len()) * 8;
                        out.push_str(&format!("    movq {stack_offset}(%rbp), %rax\n"));
                        out.push_str(&format!("    movq %rax, {offset}(%rbp)\n"));
                    }
                }
                Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
            }
        }

        self.emit_block(&self.function.body, out)?;

        if matches!(
            self.function.return_annotation,
            Some(Type::Prim(PrimType::Unit))
        ) {
            // Unit is represented as zero at native ABI boundaries.
            self.emit_i32(0, out);
        }

        match self.target {
            Target::Aarch64AppleDarwin => {
                if frame_size > 0 {
                    out.push_str(&format!("    add sp, sp, #{frame_size}\n"));
                }
                out.push_str("    ldp x29, x30, [sp], #16\n");
                out.push_str("    ret\n\n");
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    leave\n");
                out.push_str("    ret\n\n");
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
        Ok(())
    }

    fn emit_block(&mut self, block: &Block, out: &mut String) -> Result<()> {
        if block.items.is_empty() {
            self.emit_i32(0, out);
            return Ok(());
        }

        let mut last_was_expr = false;
        for item in &block.items {
            match item {
                BlockItem::Binding { name, expr, .. } => {
                    self.emit_expr(expr, out)?;
                    let offset = self.local_offset(name)?;
                    self.store_result(offset, out);
                    last_was_expr = false;
                }
                BlockItem::Expr(expr) => {
                    self.emit_expr(expr, out)?;
                    last_was_expr = true;
                }
            }
        }

        if !last_was_expr {
            self.emit_i32(0, out);
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, out: &mut String) -> Result<()> {
        match expr {
            Expr::Int(value, _) => {
                self.emit_i32(*value as u32, out);
            }
            Expr::Bool(value, _) => {
                self.emit_i32(if *value { 1 } else { 0 }, out);
            }
            Expr::String(value, _) => self.emit_string(value, out),
            Expr::Unit(_) => self.emit_i32(0, out),
            Expr::Var(name, _) => {
                if let Some(tag) = self.find_variant_tag(name) {
                    self.emit_i32(tag as u32, out);
                    return Ok(());
                }
                if self.find_program_function(name) || self.find_external_function(name).is_some() {
                    return Err(Error::new(format!(
                        "native backend does not support function value `{name}` yet"
                    )));
                }
                let offset = self.local_offset(name)?;
                match self.target {
                    Target::Aarch64AppleDarwin => {
                        out.push_str(&format!("    ldr x0, [x29, #{offset}]\n"));
                    }
                    Target::X86_64UnknownLinuxGnu => {
                        out.push_str(&format!("    movq {offset}(%rbp), %rax\n"));
                    }
                    Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
                }
            }
            Expr::Call { name, args, .. } => self.emit_call(name, args, out)?,
            Expr::MethodCall {
                receiver,
                name,
                args,
                ..
            } => self.emit_method_call(receiver, name, args, out)?,
            Expr::FieldAccess { receiver, .. } => self.emit_expr(receiver, out)?,
            Expr::StructLiteral { value, .. } => self.emit_expr(value, out)?,
            Expr::Binary {
                op, left, right, ..
            } => self.emit_binary(*op, left, right, out)?,
            Expr::Match {
                scrutinee, arms, ..
            } => {
                let end_label = self.label("match_end");
                let mut arm_labels = Vec::new();
                let mut wildcard_label = None;

                self.emit_expr(scrutinee, out)?;
                self.push_result(out);

                for (index, arm) in arms.iter().enumerate() {
                    let label = self.label(&format!("match_arm_{index}"));
                    match &arm.pattern {
                        Pattern::Wildcard => wildcard_label = Some(label.clone()),
                        Pattern::Var(_) => wildcard_label = Some(label.clone()),
                        Pattern::Int(value) => {
                            self.emit_match_i32(*value as u32, &label, out);
                        }
                        Pattern::Bool(value) => {
                            self.emit_match_i32(if *value { 1 } else { 0 }, &label, out);
                        }
                        Pattern::Unit => {
                            self.emit_match_i32(0, &label, out);
                        }
                        Pattern::Variant { name, .. } => {
                            let tag = self.variant_tag(name)? as u32;
                            self.emit_match_tag(tag, &label, out);
                        }
                    }
                    arm_labels.push((label, &arm.pattern, &arm.expr));
                }

                if let Some(label) = &wildcard_label {
                    self.emit_jump(label, out);
                }

                for (label, pattern, arm_expr) in arm_labels {
                    out.push_str(&format!("{label}:\n"));
                    self.bind_pattern_payload(pattern, out)?;
                    self.pop_match_value(out);
                    self.emit_expr(arm_expr, out)?;
                    self.emit_jump(&end_label, out);
                }

                out.push_str(&format!("{end_label}:\n"));
            }
            Expr::Lambda { .. } => {
                return Err(Error::new(
                    "native backend does not support anonymous functions yet",
                ));
            }
            Expr::Block(block, _) => self.emit_block(block, out)?,
        }
        Ok(())
    }

    fn emit_call(&mut self, name: &str, args: &[Expr], out: &mut String) -> Result<()> {
        if let Some(tag) = self.find_variant_tag(name) {
            if args.len() != 1 {
                return Err(Error::new(format!(
                    "native backend expects enum variant `{name}` to have one payload"
                )));
            }
            self.emit_expr(&args[0], out)?;
            self.pack_enum(tag as u32, out);
            return Ok(());
        }

        if let Some(function) = self.find_external_function(name) {
            let binding = function.bindings.native.as_ref().ok_or_else(|| {
                Error::new(format!(
                    "external function `{}` from `{}` does not have a native binding for target `{}`",
                    function.name,
                    format_external_path(function),
                    self.target
                ))
            })?;
            let callee = self.backend.external_symbol_name(&binding.symbol);
            return self.emit_native_call_to_symbol(&callee, args, out);
        }

        if !self.find_program_function(name) {
            return Err(Error::new(format!(
                "native backend does not support calling function value `{name}` yet"
            )));
        }

        let callee = self.backend.symbol_name(name);
        self.emit_native_call_to_symbol(&callee, args, out)
    }

    fn emit_native_call_to_symbol(
        &mut self,
        callee: &str,
        args: &[Expr],
        out: &mut String,
    ) -> Result<()> {
        if args.len() > 8 {
            return Err(Error::new(
                "native backend supports at most 8 call arguments",
            ));
        }

        match self.target {
            Target::Aarch64AppleDarwin => {
                let stack_size = align_to(args.len() as i32 * 16, 16);
                if stack_size > 0 {
                    out.push_str(&format!("    sub sp, sp, #{stack_size}\n"));
                }
                for (index, arg) in args.iter().enumerate() {
                    self.emit_expr(arg, out)?;
                    out.push_str(&format!("    str x0, [sp, #{}]\n", index * 16));
                }
                for index in 0..args.len() {
                    out.push_str(&format!("    ldr x{index}, [sp, #{}]\n", index * 16));
                }
                if stack_size > 0 {
                    out.push_str(&format!("    add sp, sp, #{stack_size}\n"));
                }
                out.push_str(&format!("    bl {callee}\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                const ARG_REGS: [&str; 6] = ["%rdi", "%rsi", "%rdx", "%rcx", "%r8", "%r9"];
                let stack_args = args.len().saturating_sub(ARG_REGS.len());
                let outgoing_size = stack_args * 8;
                let temp_offset = outgoing_size;
                let stack_size = align_to((outgoing_size + args.len() * 16) as i32, 16);
                if stack_size > 0 {
                    out.push_str(&format!("    subq ${stack_size}, %rsp\n"));
                }
                for (index, arg) in args.iter().enumerate() {
                    self.emit_expr(arg, out)?;
                    out.push_str(&format!(
                        "    movq %rax, {}(%rsp)\n",
                        temp_offset + index * 16
                    ));
                }
                for (index, reg) in ARG_REGS.iter().enumerate().take(args.len()) {
                    out.push_str(&format!(
                        "    movq {}(%rsp), {reg}\n",
                        temp_offset + index * 16
                    ));
                }
                for index in ARG_REGS.len()..args.len() {
                    out.push_str(&format!(
                        "    movq {}(%rsp), %rax\n",
                        temp_offset + index * 16
                    ));
                    out.push_str(&format!(
                        "    movq %rax, {}(%rsp)\n",
                        (index - ARG_REGS.len()) * 8
                    ));
                }
                out.push_str(&format!("    call {callee}\n"));
                if stack_size > 0 {
                    out.push_str(&format!("    addq ${stack_size}, %rsp\n"));
                }
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
        Ok(())
    }

    fn emit_method_call(
        &mut self,
        receiver: &Expr,
        name: &str,
        args: &[Expr],
        out: &mut String,
    ) -> Result<()> {
        if args.len() != 1 {
            return Err(Error::new(format!(
                "native backend only supports unary primitive method `{name}`"
            )));
        }
        self.emit_binary(method_op(name)?, receiver, &args[0], out)
    }

    fn emit_binary(
        &mut self,
        op: BinaryOp,
        left: &Expr,
        right: &Expr,
        out: &mut String,
    ) -> Result<()> {
        self.emit_expr(left, out)?;
        self.push_result(out);
        self.emit_expr(right, out)?;
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str("    ldr w9, [sp], #16\n");
                match op {
                    BinaryOp::Add => out.push_str("    add w0, w9, w0\n"),
                    BinaryOp::Sub => out.push_str("    sub w0, w9, w0\n"),
                    BinaryOp::Mul => out.push_str("    mul w0, w9, w0\n"),
                    BinaryOp::Eq => {
                        out.push_str("    cmp w9, w0\n");
                        out.push_str("    cset w0, eq\n");
                    }
                    BinaryOp::Lt => {
                        out.push_str("    cmp w9, w0\n");
                        out.push_str("    cset w0, lt\n");
                    }
                }
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    movl (%rsp), %r9d\n");
                out.push_str("    addq $16, %rsp\n");
                match op {
                    BinaryOp::Add => out.push_str("    addl %r9d, %eax\n"),
                    BinaryOp::Sub => {
                        out.push_str("    subl %eax, %r9d\n");
                        out.push_str("    movl %r9d, %eax\n");
                    }
                    BinaryOp::Mul => out.push_str("    imull %r9d, %eax\n"),
                    BinaryOp::Eq => {
                        out.push_str("    cmpl %eax, %r9d\n");
                        out.push_str("    sete %al\n");
                        out.push_str("    movzbl %al, %eax\n");
                    }
                    BinaryOp::Lt => {
                        out.push_str("    cmpl %eax, %r9d\n");
                        out.push_str("    setl %al\n");
                        out.push_str("    movzbl %al, %eax\n");
                    }
                }
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
        Ok(())
    }

    fn emit_i32(&self, value: u32, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str(&format!("    mov w0, #{value}\n")),
            Target::X86_64UnknownLinuxGnu => out.push_str(&format!("    movl ${value}, %eax\n")),
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn emit_string(&mut self, value: &str, out: &mut String) {
        let label = self.label("string");
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str(".section __TEXT,__cstring,cstring_literals\n");
                out.push_str(&format!("{label}:\n"));
                out.push_str(&format!("    .asciz \"{}\"\n", escape_asm_string(value)));
                out.push_str(".text\n");
                out.push_str(&format!("    adrp x0, {label}@PAGE\n"));
                out.push_str(&format!("    add x0, x0, {label}@PAGEOFF\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str(".section .rodata\n");
                out.push_str(&format!("{label}:\n"));
                out.push_str(&format!("    .asciz \"{}\"\n", escape_asm_string(value)));
                out.push_str(".text\n");
                out.push_str(&format!("    leaq {label}(%rip), %rax\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn pack_enum(&self, tag: u32, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str("    lsl x0, x0, #32\n");
                out.push_str(&format!("    orr x0, x0, #{tag}\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    shlq $32, %rax\n");
                out.push_str(&format!("    orq ${tag}, %rax\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn store_result(&self, offset: i32, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str(&format!("    str x0, [x29, #{offset}]\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str(&format!("    movq %rax, {offset}(%rbp)\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn push_result(&self, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str("    str x0, [sp, #-16]!\n"),
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    subq $16, %rsp\n");
                out.push_str("    movq %rax, (%rsp)\n");
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn pop_match_value(&self, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str("    add sp, sp, #16\n"),
            Target::X86_64UnknownLinuxGnu => out.push_str("    addq $16, %rsp\n"),
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn emit_match_i32(&self, value: u32, label: &str, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str("    ldr w9, [sp]\n");
                out.push_str(&format!("    mov w10, #{value}\n"));
                out.push_str("    cmp w9, w10\n");
                out.push_str(&format!("    b.eq {label}\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str(&format!("    cmpl ${value}, (%rsp)\n"));
                out.push_str(&format!("    je {label}\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn emit_match_tag(&self, tag: u32, label: &str, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str("    ldr x9, [sp]\n");
                out.push_str("    and x9, x9, #0xffffffff\n");
                out.push_str(&format!("    cmp x9, #{tag}\n"));
                out.push_str(&format!("    b.eq {label}\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    movq (%rsp), %r9\n");
                out.push_str("    andq $4294967295, %r9\n");
                out.push_str(&format!("    cmpq ${tag}, %r9\n"));
                out.push_str(&format!("    je {label}\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn emit_jump(&self, label: &str, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str(&format!("    b {label}\n")),
            Target::X86_64UnknownLinuxGnu => out.push_str(&format!("    jmp {label}\n")),
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn local_offset(&self, name: &str) -> Result<i32> {
        self.locals
            .get(name)
            .copied()
            .ok_or_else(|| Error::new(format!("internal lowering error: unknown local `{name}`")))
    }

    fn bind_pattern_payload(&self, pattern: &Pattern, out: &mut String) -> Result<()> {
        match pattern {
            Pattern::Variant {
                payload: Some(payload),
                ..
            } => self.bind_pattern_payload_value(payload, true, out),
            Pattern::Var(name) => {
                let offset = self.local_offset(name)?;
                match self.target {
                    Target::Aarch64AppleDarwin => {
                        out.push_str("    ldr x9, [sp]\n");
                        out.push_str(&format!("    str x9, [x29, #{offset}]\n"));
                    }
                    Target::X86_64UnknownLinuxGnu => {
                        out.push_str("    movq (%rsp), %r9\n");
                        out.push_str(&format!("    movq %r9, {offset}(%rbp)\n"));
                    }
                    Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
                }
                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn bind_pattern_payload_value(
        &self,
        pattern: &Pattern,
        unpack_enum: bool,
        out: &mut String,
    ) -> Result<()> {
        match pattern {
            Pattern::Var(name) => {
                let offset = self.local_offset(name)?;
                match self.target {
                    Target::Aarch64AppleDarwin => {
                        out.push_str("    ldr x9, [sp]\n");
                        if unpack_enum {
                            out.push_str("    lsr x9, x9, #32\n");
                        }
                        out.push_str(&format!("    str x9, [x29, #{offset}]\n"));
                    }
                    Target::X86_64UnknownLinuxGnu => {
                        out.push_str("    movq (%rsp), %r9\n");
                        if unpack_enum {
                            out.push_str("    shrq $32, %r9\n");
                        }
                        out.push_str(&format!("    movq %r9, {offset}(%rbp)\n"));
                    }
                    Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
                }
                Ok(())
            }
            Pattern::Wildcard | Pattern::Int(_) | Pattern::Bool(_) | Pattern::Unit => Ok(()),
            Pattern::Variant { payload, .. } => {
                if let Some(payload) = payload {
                    self.bind_pattern_payload_value(payload, true, out)
                } else {
                    Ok(())
                }
            }
        }
    }

    fn label(&mut self, prefix: &str) -> String {
        let label = format!("L_{}_{}_{}", self.label_prefix, prefix, self.next_label);
        self.next_label += 1;
        label
    }

    fn variant_tag(&self, name: &str) -> Result<usize> {
        self.find_variant_tag(name)
            .ok_or_else(|| Error::new(format!("internal lowering error: unknown variant `{name}`")))
    }

    fn find_variant_tag(&self, name: &str) -> Option<usize> {
        self.program
            .items
            .iter()
            .find_map(|item| {
                let TopLevelItem::Enum(decl) = item else {
                    return None;
                };
                decl.variants
                    .iter()
                    .position(|variant| variant.name == name)
            })
            .or_else(|| builtin_variant_tag(name))
    }

    fn find_external_function(&self, name: &str) -> Option<&ExternalFunction> {
        self.program.items.iter().find_map(|item| {
            let TopLevelItem::Import(import) = item else {
                return None;
            };
            if import.name == name {
                self.platform
                    .externs
                    .resolve_import(&import.path, &import.name)
            } else {
                None
            }
        })
    }

    fn find_program_function(&self, name: &str) -> bool {
        self.program
            .functions()
            .iter()
            .any(|function| function.name == name)
    }
}

fn collect_block_bindings(block: &Block, locals: &mut HashMap<String, i32>, next_slot: &mut i32) {
    for item in &block.items {
        match item {
            BlockItem::Binding { name, expr, .. } => {
                locals.entry(name.clone()).or_insert_with(|| {
                    let offset = -8 * *next_slot;
                    *next_slot += 1;
                    offset
                });
                collect_expr_bindings(expr, locals, next_slot);
            }
            BlockItem::Expr(expr) => collect_expr_bindings(expr, locals, next_slot),
        }
    }
}

fn collect_expr_bindings(expr: &Expr, locals: &mut HashMap<String, i32>, next_slot: &mut i32) {
    match expr {
        Expr::Call { args, .. } => {
            for arg in args {
                collect_expr_bindings(arg, locals, next_slot);
            }
        }
        Expr::MethodCall { receiver, args, .. } => {
            collect_expr_bindings(receiver, locals, next_slot);
            for arg in args {
                collect_expr_bindings(arg, locals, next_slot);
            }
        }
        Expr::FieldAccess { receiver, .. } => collect_expr_bindings(receiver, locals, next_slot),
        Expr::StructLiteral { value, .. } => collect_expr_bindings(value, locals, next_slot),
        Expr::Binary { left, right, .. } => {
            collect_expr_bindings(left, locals, next_slot);
            collect_expr_bindings(right, locals, next_slot);
        }
        Expr::Match {
            scrutinee, arms, ..
        } => {
            collect_expr_bindings(scrutinee, locals, next_slot);
            for arm in arms {
                collect_pattern_bindings(&arm.pattern, locals, next_slot);
                collect_expr_bindings(&arm.expr, locals, next_slot);
            }
        }
        Expr::Lambda { body, .. } => collect_expr_bindings(body, locals, next_slot),
        Expr::Block(block, _) => collect_block_bindings(block, locals, next_slot),
        Expr::Int(_, _)
        | Expr::Bool(_, _)
        | Expr::String(_, _)
        | Expr::Unit(_)
        | Expr::Var(_, _) => {}
    }
}

fn collect_pattern_bindings(
    pattern: &Pattern,
    locals: &mut HashMap<String, i32>,
    next_slot: &mut i32,
) {
    match pattern {
        Pattern::Var(name) => {
            locals.entry(name.clone()).or_insert_with(|| {
                let offset = -8 * *next_slot;
                *next_slot += 1;
                offset
            });
        }
        Pattern::Variant {
            payload: Some(payload),
            ..
        } => collect_pattern_bindings(payload, locals, next_slot),
        Pattern::Int(_)
        | Pattern::Bool(_)
        | Pattern::Unit
        | Pattern::Wildcard
        | Pattern::Variant { payload: None, .. } => {}
    }
}

fn method_op(name: &str) -> Result<BinaryOp> {
    match name {
        "add" => Ok(BinaryOp::Add),
        "sub" => Ok(BinaryOp::Sub),
        "mul" => Ok(BinaryOp::Mul),
        "eq" => Ok(BinaryOp::Eq),
        "lt" => Ok(BinaryOp::Lt),
        _ => Err(Error::new(format!(
            "native backend does not support method `{name}`"
        ))),
    }
}

fn builtin_variant_tag(name: &str) -> Option<usize> {
    match name {
        "Ok" | "Unsupported" => Some(0),
        "Err" | "Unavailable" => Some(1),
        "Interrupted" => Some(2),
        "InvalidUtf8" => Some(3),
        "Unknown" => Some(4),
        _ => None,
    }
}

fn base_symbol_name(name: &str) -> String {
    name.strip_suffix('!')
        .map(|base| format!("{base}_effect"))
        .unwrap_or_else(|| name.to_string())
}

fn sanitize_label(value: &str) -> String {
    value
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect()
}

fn escape_asm_string(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            ch if ch.is_ascii_graphic() || ch == ' ' => out.push(ch),
            ch => out.push_str(&format!("\\{:03o}", ch as u32)),
        }
    }
    out
}

fn align_to(value: i32, align: i32) -> i32 {
    if value == 0 {
        0
    } else {
        ((value + align - 1) / align) * align
    }
}

struct JsEmitter<'a> {
    platform: &'a PlatformSpec,
    program: &'a Program,
    emit_entrypoint: bool,
}

impl<'a> JsEmitter<'a> {
    fn new(platform: &'a PlatformSpec, program: &'a Program, emit_entrypoint: bool) -> Self {
        Self {
            platform,
            program,
            emit_entrypoint,
        }
    }

    fn emit_program(&mut self) -> Result<String> {
        let mut out = String::new();
        out.push_str("// Generated by the Emela compiler.\n");
        out.push_str("\"use strict\";\n\n");
        self.emit_runtime_prelude(&mut out)?;
        for function in self.program.functions() {
            self.emit_function(function, &mut out)?;
            out.push('\n');
        }
        if !self.emit_entrypoint {
            return Ok(out);
        }
        let entry = self
            .program
            .functions()
            .into_iter()
            .find(|function| function.name == "main" || function.name == "main!")
            .ok_or_else(|| Error::new("internal js lowering error: missing main"))?;
        out.push_str(&format!(
            "const __emela_result = {}();\n",
            sanitize_ident(&entry.name)
        ));
        out.push_str("if (typeof process !== \"undefined\" && process.exitCode === undefined) {\n");
        out.push_str(
            "  process.exitCode = Number.isInteger(__emela_result) ? __emela_result : 0;\n",
        );
        out.push_str("}\n");
        Ok(out)
    }

    fn emit_runtime_prelude(&self, out: &mut String) -> Result<()> {
        for item in &self.program.items {
            let TopLevelItem::Import(import) = item else {
                continue;
            };
            let Some(function) = self
                .platform
                .externs
                .resolve_import(&import.path, &import.name)
            else {
                continue;
            };
            let Some(symbol) = function.bindings.js_symbol.as_deref() else {
                continue;
            };
            match symbol {
                "__emela_write_stdout_utf8" | "__emela_read_stdin_utf8" | "__emela_now_i32" => {
                    let runtime =
                        super::bundled::js_runtime(&self.platform.name).ok_or_else(|| {
                            Error::new(format!(
                                "platform `{}` does not have a bundled js runtime",
                                self.platform.name
                            ))
                        })?;
                    out.push_str(runtime);
                    out.push_str("\n\n");
                    return Ok(());
                }
                _ => {}
            }
        }
        Ok(())
    }

    fn emit_function(&mut self, function: &Function, out: &mut String) -> Result<()> {
        let params = function
            .params
            .iter()
            .map(|param| sanitize_ident(&param.name))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "function {}({params}) ",
            sanitize_ident(&function.name)
        ));
        self.emit_block_body(&function.body, out, 0)
    }

    fn emit_block_body(&mut self, block: &Block, out: &mut String, indent: usize) -> Result<()> {
        out.push_str("{\n");
        if block.items.is_empty() {
            self.line(out, indent + 1, "return undefined;");
            self.line(out, indent, "}");
            return Ok(());
        }
        for (index, item) in block.items.iter().enumerate() {
            let is_last = index + 1 == block.items.len();
            match item {
                BlockItem::Binding { name, expr, .. } => {
                    let expr = self.emit_expr(expr)?;
                    self.line(
                        out,
                        indent + 1,
                        &format!("let {} = {expr};", sanitize_ident(name)),
                    );
                }
                BlockItem::Expr(expr) if is_last => {
                    let expr = self.emit_expr(expr)?;
                    self.line(out, indent + 1, &format!("return {expr};"));
                }
                BlockItem::Expr(expr) => {
                    let expr = self.emit_expr(expr)?;
                    self.line(out, indent + 1, &format!("{expr};"));
                }
            }
        }
        if !matches!(block.items.last(), Some(BlockItem::Expr(_))) {
            self.line(out, indent + 1, "return undefined;");
        }
        self.line(out, indent, "}");
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr) -> Result<String> {
        match expr {
            Expr::Int(value, _) => Ok(value.to_string()),
            Expr::Bool(value, _) => Ok(value.to_string()),
            Expr::String(value, _) => serde_json::to_string(value)
                .map_err(|err| Error::new(format!("failed to encode string literal: {err}"))),
            Expr::Unit(_) => Ok("undefined".to_string()),
            Expr::Var(name, _) => {
                if let Some(tag) = self.find_variant_tag(name) {
                    return Ok(format!("{{ tag: {tag}, value: undefined }}"));
                }
                if self.find_program_function(name) {
                    return Ok(sanitize_ident(name));
                }
                if let Some(function) = self.find_external_function(name) {
                    let callee = function.bindings.js_symbol.as_ref().ok_or_else(|| {
                        Error::new(format!(
                            "external function `{}` from `{}` does not have a js binding",
                            function.name,
                            format_external_path(function)
                        ))
                    })?;
                    return Ok(callee.clone());
                }
                Ok(sanitize_ident(name))
            }
            Expr::Call { name, args, .. } => self.emit_call(name, args),
            Expr::MethodCall {
                receiver,
                name,
                args,
                ..
            } => self.emit_method_call(receiver, name, args),
            Expr::FieldAccess {
                receiver, field, ..
            } => Ok(format!(
                "({}).{}",
                self.emit_expr(receiver)?,
                sanitize_ident(field)
            )),
            Expr::StructLiteral { field, value, .. } => Ok(format!(
                "{{ {}: {} }}",
                sanitize_ident(field),
                self.emit_expr(value)?
            )),
            Expr::Binary {
                op, left, right, ..
            } => self.emit_binary(*op, left, right),
            Expr::Match {
                scrutinee, arms, ..
            } => self.emit_match(scrutinee, arms),
            Expr::Lambda { params, body, .. } => {
                let params = params
                    .iter()
                    .map(|param| sanitize_ident(&param.name))
                    .collect::<Vec<_>>()
                    .join(", ");
                let body = self.emit_expr(body)?;
                Ok(format!("(({params}) => {body})"))
            }
            Expr::Block(block, _) => {
                let mut out = String::new();
                out.push_str("(() => ");
                self.emit_block_body(block, &mut out, 0)?;
                out.push_str(")()");
                Ok(out)
            }
        }
    }

    fn emit_call(&mut self, name: &str, args: &[Expr]) -> Result<String> {
        let args = args
            .iter()
            .map(|arg| self.emit_expr(arg))
            .collect::<Result<Vec<_>>>()?
            .join(", ");
        if let Some(tag) = self.find_variant_tag(name) {
            return Ok(format!("{{ tag: {tag}, value: {args} }}"));
        }
        if let Some(function) = self.find_external_function(name) {
            let callee = function.bindings.js_symbol.as_ref().ok_or_else(|| {
                Error::new(format!(
                    "external function `{}` from `{}` does not have a js binding",
                    function.name,
                    format_external_path(function)
                ))
            })?;
            return Ok(format!("{callee}({args})"));
        }
        Ok(format!("{}({args})", sanitize_ident(name)))
    }

    fn emit_method_call(&mut self, receiver: &Expr, name: &str, args: &[Expr]) -> Result<String> {
        if args.len() != 1 {
            return Err(Error::new(format!(
                "js backend only supports unary primitive method `{name}`"
            )));
        }
        self.emit_binary(method_op(name)?, receiver, &args[0])
    }

    fn emit_binary(&mut self, op: BinaryOp, left: &Expr, right: &Expr) -> Result<String> {
        let left = self.emit_expr(left)?;
        let right = self.emit_expr(right)?;
        let op = match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Eq => "===",
            BinaryOp::Lt => "<",
        };
        Ok(format!("({left} {op} {right})"))
    }

    fn emit_match(&mut self, scrutinee: &Expr, arms: &[MatchArm]) -> Result<String> {
        let mut out = String::new();
        out.push_str("(() => {\n");
        out.push_str(&format!(
            "  const __match = {};\n",
            self.emit_expr(scrutinee)?
        ));
        for arm in arms {
            let condition = self.pattern_condition(&arm.pattern, "__match")?;
            out.push_str(&format!("  if ({condition}) {{\n"));
            self.emit_pattern_bindings(&arm.pattern, "__match", &mut out, 2)?;
            out.push_str(&format!("    return {};\n", self.emit_expr(&arm.expr)?));
            out.push_str("  }\n");
        }
        out.push_str("  throw new Error(\"non-exhaustive match\");\n");
        out.push_str("})()");
        Ok(out)
    }

    fn pattern_condition(&self, pattern: &Pattern, value: &str) -> Result<String> {
        match pattern {
            Pattern::Int(value_i32) => Ok(format!("{value} === {value_i32}")),
            Pattern::Bool(value_bool) => Ok(format!("{value} === {value_bool}")),
            Pattern::Unit => Ok(format!("{value} === undefined")),
            Pattern::Var(_) | Pattern::Wildcard => Ok("true".to_string()),
            Pattern::Variant { name, .. } => {
                let tag = self.variant_tag(name)?;
                Ok(format!("{value}.tag === {tag}"))
            }
        }
    }

    fn emit_pattern_bindings(
        &self,
        pattern: &Pattern,
        value: &str,
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        match pattern {
            Pattern::Var(name) => {
                self.line(
                    out,
                    indent,
                    &format!("const {} = {value};", sanitize_ident(name)),
                );
            }
            Pattern::Variant {
                payload: Some(payload),
                ..
            } => self.emit_pattern_bindings(payload, &format!("{value}.value"), out, indent)?,
            Pattern::Int(_)
            | Pattern::Bool(_)
            | Pattern::Unit
            | Pattern::Wildcard
            | Pattern::Variant { payload: None, .. } => {}
        }
        Ok(())
    }

    fn line(&self, out: &mut String, indent: usize, value: &str) {
        out.push_str(&"  ".repeat(indent));
        out.push_str(value);
        out.push('\n');
    }

    fn variant_tag(&self, name: &str) -> Result<usize> {
        self.find_variant_tag(name).ok_or_else(|| {
            Error::new(format!(
                "internal js lowering error: unknown variant `{name}`"
            ))
        })
    }

    fn find_variant_tag(&self, name: &str) -> Option<usize> {
        self.program
            .items
            .iter()
            .find_map(|item| {
                let TopLevelItem::Enum(decl) = item else {
                    return None;
                };
                decl.variants
                    .iter()
                    .position(|variant| variant.name == name)
            })
            .or_else(|| builtin_variant_tag(name))
    }

    fn find_external_function(&self, name: &str) -> Option<&ExternalFunction> {
        self.program.items.iter().find_map(|item| {
            let TopLevelItem::Import(import) = item else {
                return None;
            };
            if import.name == name {
                self.platform
                    .externs
                    .resolve_import(&import.path, &import.name)
            } else {
                None
            }
        })
    }

    fn find_program_function(&self, name: &str) -> bool {
        self.program
            .functions()
            .iter()
            .any(|function| function.name == name)
    }
}

fn sanitize_ident(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        let valid = ch == '_' || ch == '$' || ch.is_ascii_alphanumeric();
        if valid && !(index == 0 && ch.is_ascii_digit()) {
            out.push(ch);
        } else if ch == '!' {
            out.push_str("_effect");
        } else {
            out.push('_');
        }
    }
    out
}

pub(crate) fn emit_wasm(program: &Program) -> Result<String> {
    let emitter = WasmEmitter::new(program, WasmMode::Standalone, None, false);
    emitter.emit_program()
}

pub(crate) fn emit_wasm_library(program: &Program) -> Result<String> {
    let emitter = WasmEmitter::new(program, WasmMode::Standalone, None, true);
    emitter.emit_program()
}

pub(crate) fn emit_wasi(program: &Program, platform: &PlatformSpec) -> Result<String> {
    let emitter = WasmEmitter::new(program, WasmMode::Wasi, Some(platform), false);
    emitter.emit_program()
}

pub(crate) fn emit_wasi_library(program: &Program, platform: &PlatformSpec) -> Result<String> {
    let emitter = WasmEmitter::new(program, WasmMode::Wasi, Some(platform), true);
    emitter.emit_program()
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum WasmMode {
    Standalone,
    Wasi,
}

struct WasmEmitter<'a> {
    program: &'a Program,
    mode: WasmMode,
    platform: Option<&'a PlatformSpec>,
    is_library: bool,
    string_offsets: HashMap<String, i32>,
    string_data: Vec<u8>,
}

impl<'a> WasmEmitter<'a> {
    fn new(
        program: &'a Program,
        mode: WasmMode,
        platform: Option<&'a PlatformSpec>,
        is_library: bool,
    ) -> Self {
        let (string_offsets, string_data) = collect_string_data(program);
        Self {
            program,
            mode,
            platform,
            is_library,
            string_offsets,
            string_data,
        }
    }

    fn emit_program(&self) -> Result<String> {
        let mut out = String::new();
        wat_line(&mut out, 0, ";; Generated by the Emela compiler.");
        out.push_str("(module\n");

        if self.mode == WasmMode::Wasi && self.string_data.len() > 0x1000 {
            return Err(Error::new(format!(
                "wasi backend string data ({} bytes) exceeds 4KB limit; would overlap I/O workspace at 0x1000",
                self.string_data.len()
            )));
        }

        self.emit_wasi_imports(&mut out)?;

        let has_data = !self.string_data.is_empty();
        let needs_memory = has_data || self.mode == WasmMode::Wasi;
        if needs_memory {
            if self.mode == WasmMode::Wasi {
                wat_line(&mut out, 1, "(memory (export \"memory\") 2)");
            } else {
                wat_line(&mut out, 1, "(memory 1)");
            }
        }

        if !self.string_data.is_empty() {
            out.push_str("  (data (i32.const 0) \"");
            for &byte in &self.string_data {
                match byte {
                    b'\\' => out.push_str("\\\\"),
                    b'\"' => out.push_str("\\\""),
                    b'\n' => out.push_str("\\n"),
                    b'\t' => out.push_str("\\t"),
                    b'\r' => out.push_str("\\r"),
                    0x20..=0x7E => out.push(byte as char),
                    _ => out.push_str(&format!("\\{:02x}", byte)),
                }
            }
            out.push_str("\")\n\n");
        } else if self.mode == WasmMode::Wasi {
            out.push('\n');
        }

        self.emit_glue_helpers(&mut out)?;

        for function in self.program.functions() {
            self.emit_function(function, &mut out)?;
        }

        for function in self.program.functions() {
            let name = sanitize_ident(&function.name);
            wat_line(
                &mut out,
                1,
                &format!("(export \"{}\" (func ${name}))", function.name),
            );
        }

        if self.mode == WasmMode::Wasi && !self.is_library {
            self.emit_wasi_start(&mut out);
        }

        out.push_str(")\n");
        Ok(out)
    }

    fn emit_function(&self, function: &Function, out: &mut String) -> Result<()> {
        let locals = collect_wasm_locals(function);
        let param_count = function.params.len();
        let name = sanitize_ident(&function.name);
        let result_type = wasm_result_type(&function.return_annotation, self.program);

        out.push_str("  (func $");
        out.push_str(&name);
        for param in &function.params {
            out.push_str(&format!(" (param ${} i32)", sanitize_ident(&param.name)));
        }
        out.push_str(&format!(" (result {result_type})\n"));

        for local in locals.iter().skip(param_count) {
            wat_line(out, 2, &format!("(local ${} i32)", sanitize_ident(local)));
        }

        let return_unit = matches!(function.return_annotation, Some(Type::Prim(PrimType::Unit)));

        self.emit_block_body(&function.body, &locals, out, 2, return_unit, result_type)?;

        out.push_str("  )\n\n");
        Ok(())
    }

    fn emit_block_body(
        &self,
        block: &Block,
        locals: &[String],
        out: &mut String,
        indent: usize,
        return_unit: bool,
        result_type: &str,
    ) -> Result<()> {
        if block.items.is_empty() {
            wat_line(out, indent, &format!("{result_type}.const 0"));
            return Ok(());
        }

        let last_idx = block.items.len() - 1;
        for (index, item) in block.items.iter().enumerate() {
            let is_last = index == last_idx;
            match item {
                BlockItem::Binding { name, expr, .. } => {
                    self.emit_expr(expr, locals, out, indent)?;
                    wat_line(out, indent, &format!("local.set ${}", sanitize_ident(name)));
                }
                BlockItem::Expr(expr) => {
                    self.emit_expr(expr, locals, out, indent)?;
                    if !is_last {
                        wat_line(out, indent, "drop");
                    } else if return_unit {
                        wat_line(out, indent, "drop");
                        wat_line(out, indent, "i32.const 0");
                    }
                }
            }
        }

        if !matches!(block.items.last(), Some(BlockItem::Expr(_))) {
            wat_line(out, indent, &format!("{result_type}.const 0"));
        }
        Ok(())
    }

    fn emit_expr(
        &self,
        expr: &Expr,
        locals: &[String],
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        match expr {
            Expr::Int(value, _) => {
                wat_line(out, indent, &format!("i32.const {}", *value as u32));
                Ok(())
            }
            Expr::Bool(value, _) => {
                wat_line(
                    out,
                    indent,
                    if *value { "i32.const 1" } else { "i32.const 0" },
                );
                Ok(())
            }
            Expr::String(value, _) => {
                let offset = self.string_offsets.get(value).copied().unwrap_or(0);
                wat_line(out, indent, &format!("i32.const {offset}"));
                Ok(())
            }
            Expr::Unit(_) => {
                wat_line(out, indent, "i32.const 0");
                Ok(())
            }
            Expr::Var(name, _) => {
                if let Some(tag) = self.find_variant_tag(name) {
                    self.push_unit_payload(out, indent);
                    self.pack_enum(tag as u32, "i32", out, indent);
                    return Ok(());
                }
                if self.find_program_function(name) || self.find_external_function(name).is_some() {
                    return Err(Error::new(format!(
                        "wasm backend does not support function value `{name}` yet"
                    )));
                }
                let idx = local_index(locals, name)?;
                wat_line(out, indent, &format!("local.get {}", idx));
                Ok(())
            }
            Expr::Call { name, args, .. } => self.emit_call(name, args, locals, out, indent),
            Expr::MethodCall {
                receiver,
                name,
                args,
                ..
            } => self.emit_method_call(receiver, name, args, locals, out, indent),
            Expr::FieldAccess { receiver, .. } => self.emit_expr(receiver, locals, out, indent),
            Expr::StructLiteral { value, .. } => self.emit_expr(value, locals, out, indent),
            Expr::Binary {
                op, left, right, ..
            } => self.emit_binary(*op, left, right, locals, out, indent),
            Expr::Match {
                scrutinee, arms, ..
            } => self.emit_match(scrutinee, arms, locals, out, indent),
            Expr::Lambda { .. } => Err(Error::new(
                "wasm backend does not support anonymous functions yet",
            )),
            Expr::Block(block, _) => {
                let result_type = expression_natural_type(expr, self.program);
                self.emit_block_body(block, locals, out, indent, false, result_type)
            }
        }
    }

    fn emit_call(
        &self,
        name: &str,
        args: &[Expr],
        locals: &[String],
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        if let Some(tag) = self.find_variant_tag(name) {
            if args.len() != 1 {
                return Err(Error::new(format!(
                    "wasm backend expects enum variant `{name}` to have one payload"
                )));
            }
            self.emit_expr(&args[0], locals, out, indent)?;
            let payload_type = expression_natural_type(&args[0], self.program);
            self.pack_enum(tag as u32, payload_type, out, indent);
            return Ok(());
        }

        if self.find_external_function(name).is_some() {
            match self.mode {
                WasmMode::Wasi => {
                    for arg in args {
                        self.emit_expr(arg, locals, out, indent)?;
                    }
                    let glue_name = wasi_glue_name(name);
                    wat_line(out, indent, &format!("call ${glue_name}"));
                    return Ok(());
                }
                WasmMode::Standalone => {
                    return Err(Error::new(format!(
                        "wasm backend does not support external function calls (no capabilities for wasm32-unknown-unknown)"
                    )));
                }
            }
        }

        if !self.find_program_function(name) {
            return Err(Error::new(format!(
                "wasm backend does not support calling function value `{name}` yet"
            )));
        }

        for arg in args {
            self.emit_expr(arg, locals, out, indent)?;
        }
        let callee = sanitize_ident(name);
        wat_line(out, indent, &format!("call ${callee}"));
        Ok(())
    }

    fn emit_method_call(
        &self,
        receiver: &Expr,
        name: &str,
        args: &[Expr],
        locals: &[String],
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        if args.len() != 1 {
            return Err(Error::new(format!(
                "wasm backend only supports unary primitive method `{name}`"
            )));
        }
        self.emit_binary(method_op(name)?, receiver, &args[0], locals, out, indent)
    }

    fn emit_binary(
        &self,
        op: BinaryOp,
        left: &Expr,
        right: &Expr,
        locals: &[String],
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        self.emit_expr(left, locals, out, indent)?;
        self.emit_expr(right, locals, out, indent)?;
        match op {
            BinaryOp::Add => wat_line(out, indent, "i32.add"),
            BinaryOp::Sub => wat_line(out, indent, "i32.sub"),
            BinaryOp::Mul => wat_line(out, indent, "i32.mul"),
            BinaryOp::Eq => wat_line(out, indent, "i32.eq"),
            BinaryOp::Lt => wat_line(out, indent, "i32.lt_s"),
        }
        Ok(())
    }

    fn emit_match(
        &self,
        scrutinee: &Expr,
        arms: &[MatchArm],
        locals: &[String],
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        if arms.is_empty() {
            wat_line(out, indent, "i32.const 0");
            return Ok(());
        }
        self.emit_match_chain(scrutinee, arms, 0, locals, out, indent)
    }

    fn emit_match_chain(
        &self,
        scrutinee: &Expr,
        arms: &[MatchArm],
        arm_idx: usize,
        locals: &[String],
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        if arm_idx >= arms.len() {
            let fallback_type = expression_natural_type(&arms[0].expr, self.program);
            wat_line(out, indent, &format!("{fallback_type}.const 0"));
            return Ok(());
        }

        let arm = &arms[arm_idx];
        let is_wildcard = matches!(&arm.pattern, Pattern::Wildcard | Pattern::Var(_));

        if is_wildcard {
            self.emit_match_arm_body(scrutinee, arm, locals, out, indent)?;
            return Ok(());
        }

        let arm_result_type = expression_natural_type(&arm.expr, self.program);
        self.emit_match_condition(scrutinee, &arm.pattern, locals, out, indent)?;
        wat_line(out, indent, &format!("(if (result {arm_result_type})"));
        wat_line(out, indent + 1, "(then");
        self.emit_match_arm_body(scrutinee, arm, locals, out, indent + 2)?;
        wat_line(out, indent + 1, ")");
        wat_line(out, indent + 1, "(else");
        self.emit_match_chain(scrutinee, arms, arm_idx + 1, locals, out, indent + 2)?;
        wat_line(out, indent + 1, ")");
        wat_line(out, indent, ")");
        Ok(())
    }

    fn emit_match_condition(
        &self,
        scrutinee: &Expr,
        pattern: &Pattern,
        locals: &[String],
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        match pattern {
            Pattern::Int(value) => {
                self.emit_expr(scrutinee, locals, out, indent)?;
                wat_line(out, indent, &format!("i32.const {}", *value as u32));
                wat_line(out, indent, "i32.eq");
            }
            Pattern::Bool(value) => {
                self.emit_expr(scrutinee, locals, out, indent)?;
                wat_line(
                    out,
                    indent,
                    if *value { "i32.const 1" } else { "i32.const 0" },
                );
                wat_line(out, indent, "i32.eq");
            }
            Pattern::Unit => {
                self.emit_expr(scrutinee, locals, out, indent)?;
                wat_line(out, indent, "i32.const 0");
                wat_line(out, indent, "i32.eq");
            }
            Pattern::Variant { name, .. } => {
                let tag = self.variant_tag(name)? as u32;
                self.emit_expr(scrutinee, locals, out, indent)?;
                wat_line(out, indent, "i64.const 4294967295");
                wat_line(out, indent, "i64.and");
                wat_line(out, indent, "i32.wrap_i64");
                wat_line(out, indent, &format!("i32.const {}", tag));
                wat_line(out, indent, "i32.eq");
            }
            Pattern::Var(_) | Pattern::Wildcard => {
                wat_line(out, indent, "i32.const 1");
            }
        }
        Ok(())
    }

    fn emit_match_arm_body(
        &self,
        scrutinee: &Expr,
        arm: &MatchArm,
        locals: &[String],
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        self.emit_pattern_bindings(scrutinee, &arm.pattern, locals, out, indent)?;
        self.emit_expr(&arm.expr, locals, out, indent)
    }

    fn emit_pattern_bindings(
        &self,
        scrutinee: &Expr,
        pattern: &Pattern,
        locals: &[String],
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        match pattern {
            Pattern::Var(name) => {
                self.emit_expr(scrutinee, locals, out, indent)?;
                let idx = local_index(locals, name)?;
                wat_line(out, indent, &format!("local.set {}", idx));
            }
            Pattern::Variant {
                payload: Some(payload),
                ..
            } => {
                self.emit_expr(scrutinee, locals, out, indent)?;
                wat_line(out, indent, "i64.const 32");
                wat_line(out, indent, "i64.shr_u");
                wat_line(out, indent, "i32.wrap_i64");
                let synthetic = Pattern::Wildcard;
                self.emit_pattern_bindings_sub(&synthetic, payload, locals, out, indent)?;
            }
            Pattern::Int(_)
            | Pattern::Bool(_)
            | Pattern::Unit
            | Pattern::Wildcard
            | Pattern::Variant { payload: None, .. } => {}
        }
        Ok(())
    }

    fn emit_pattern_bindings_sub(
        &self,
        _parent: &Pattern,
        payload: &Pattern,
        locals: &[String],
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        match payload {
            Pattern::Var(name) => {
                let idx = local_index(locals, name)?;
                wat_line(out, indent, &format!("local.set {}", idx));
            }
            Pattern::Variant {
                payload: Some(inner),
                ..
            } => {
                wat_line(out, indent, "i64.const 32");
                wat_line(out, indent, "i64.shr_u");
                wat_line(out, indent, "i32.wrap_i64");
                self.emit_pattern_bindings_sub(payload, inner, locals, out, indent)?;
            }
            Pattern::Wildcard => {
                wat_line(out, indent, "drop");
            }
            _ => {}
        }
        Ok(())
    }

    fn find_variant_tag(&self, name: &str) -> Option<usize> {
        self.program
            .items
            .iter()
            .find_map(|item| {
                let TopLevelItem::Enum(decl) = item else {
                    return None;
                };
                decl.variants
                    .iter()
                    .position(|variant| variant.name == name)
            })
            .or_else(|| builtin_variant_tag(name))
    }

    fn find_external_function(&self, name: &str) -> Option<&ExternalFunction> {
        match self.mode {
            WasmMode::Standalone => None,
            WasmMode::Wasi => {
                let platform = self.platform?;
                self.program.items.iter().find_map(|item| {
                    let TopLevelItem::Import(import) = item else {
                        return None;
                    };
                    if import.name == name {
                        platform.externs.resolve_import(&import.path, &import.name)
                    } else {
                        None
                    }
                })
            }
        }
    }

    fn find_program_function(&self, name: &str) -> bool {
        self.program
            .functions()
            .iter()
            .any(|function| function.name == name)
    }

    fn variant_tag(&self, name: &str) -> Result<usize> {
        self.find_variant_tag(name).ok_or_else(|| {
            Error::new(format!(
                "internal wasm lowering error: unknown variant `{name}`"
            ))
        })
    }

    fn pack_enum(&self, tag: u32, payload_type: &str, out: &mut String, indent: usize) {
        // pack: (payload << 32) | tag
        // Caller is responsible for pushing the payload on the stack first;
        // use push_unit_payload to push a zero payload for unit variants.
        // payload_type indicates whether the stack value is "i32" or "i64" (nested enum).
        if payload_type == "i64" {
            wat_line(out, indent, "i64.const 32");
            wat_line(out, indent, "i64.shl");
        } else {
            wat_line(out, indent, "i64.extend_i32_u");
            wat_line(out, indent, "i64.const 32");
            wat_line(out, indent, "i64.shl");
        }
        wat_line(out, indent, &format!("i64.const {}", tag));
        wat_line(out, indent, "i64.or");
    }

    fn push_unit_payload(&self, out: &mut String, indent: usize) {
        wat_line(out, indent, "i32.const 0");
    }

    fn emit_wasi_imports(&self, out: &mut String) -> Result<()> {
        if self.mode != WasmMode::Wasi {
            return Ok(());
        }
        for import_name in [
            "fd_write",
            "fd_read",
            "clock_time_get",
            "random_get",
            "path_open",
            "fd_close",
            "environ_sizes_get",
            "environ_get",
            "proc_exit",
        ]
        .iter()
        {
            if *import_name == "proc_exit" && self.is_library {
                continue;
            }
            let (params_str, result_str) = wasi_import_sig(import_name);
            wat_line(
                out,
                1,
                &format!(
                    "(import \"wasi_snapshot_preview1\" \"{}\" (func ${} {}))",
                    import_name,
                    wasi_import_func_name(import_name),
                    format_wasi_sig(params_str, result_str)
                ),
            );
        }
        Ok(())
    }

    fn emit_glue_helpers(&self, out: &mut String) -> Result<()> {
        if self.mode != WasmMode::Wasi {
            return Ok(());
        }
        out.push_str(super::bundled::WASI_RUNTIME_WAT);
        out.push_str("\n\n");
        Ok(())
    }

    fn emit_wasi_start(&self, out: &mut String) {
        out.push_str("  (func $_start\n");
        let functions = self.program.functions();
        let entry = functions
            .iter()
            .find(|f| f.name == "main" || f.name == "main!");
        if let Some(main_func) = entry {
            let name = sanitize_ident(&main_func.name);
            wat_line(out, 2, &format!("call ${name}"));
            wat_line(out, 2, "drop");
        }
        wat_line(out, 2, "i32.const 0");
        wat_line(out, 2, "call $wasi_proc_exit");
        out.push_str("  )\n\n");
        wat_line(out, 1, "(export \"_start\" (func $_start))");
    }
}

fn collect_string_data(program: &Program) -> (HashMap<String, i32>, Vec<u8>) {
    let mut strings: Vec<String> = Vec::new();
    for function in program.functions() {
        collect_function_strings(function, &mut strings);
    }
    let mut offsets = HashMap::new();
    let mut data = Vec::new();
    let mut offset = 0i32;
    for s in &strings {
        offsets.insert(s.clone(), offset);
        data.extend_from_slice(s.as_bytes());
        data.push(0);
        offset += s.len() as i32 + 1;
    }
    (offsets, data)
}

fn collect_function_strings(function: &Function, strings: &mut Vec<String>) {
    collect_block_strings(&function.body, strings);
}

fn collect_block_strings(block: &Block, strings: &mut Vec<String>) {
    for item in &block.items {
        match item {
            BlockItem::Binding { expr, .. } => collect_expr_strings(expr, strings),
            BlockItem::Expr(expr) => collect_expr_strings(expr, strings),
        }
    }
}

fn collect_expr_strings(expr: &Expr, strings: &mut Vec<String>) {
    match expr {
        Expr::String(value, _) => {
            if !strings.contains(value) {
                strings.push(value.clone());
            }
        }
        Expr::Call { args, .. } => {
            for arg in args {
                collect_expr_strings(arg, strings);
            }
        }
        Expr::MethodCall { receiver, args, .. } => {
            collect_expr_strings(receiver, strings);
            for arg in args {
                collect_expr_strings(arg, strings);
            }
        }
        Expr::FieldAccess { receiver, .. } => collect_expr_strings(receiver, strings),
        Expr::StructLiteral { value, .. } => collect_expr_strings(value, strings),
        Expr::Binary { left, right, .. } => {
            collect_expr_strings(left, strings);
            collect_expr_strings(right, strings);
        }
        Expr::Match {
            scrutinee, arms, ..
        } => {
            collect_expr_strings(scrutinee, strings);
            for arm in arms {
                collect_expr_strings(&arm.expr, strings);
            }
        }
        Expr::Lambda { body, .. } => collect_expr_strings(body, strings),
        Expr::Block(block, _) => collect_block_strings(block, strings),
        Expr::Int(_, _) | Expr::Bool(_, _) | Expr::Unit(_) | Expr::Var(_, _) => {}
    }
}

fn collect_wasm_locals(function: &Function) -> Vec<String> {
    let mut locals = Vec::new();
    for param in &function.params {
        locals.push(param.name.clone());
    }
    collect_block_wasm_locals(&function.body, &mut locals);
    locals
}

fn collect_block_wasm_locals(block: &Block, locals: &mut Vec<String>) {
    for item in &block.items {
        match item {
            BlockItem::Binding { name, expr, .. } => {
                if !locals.contains(name) {
                    locals.push(name.clone());
                }
                collect_expr_wasm_locals(expr, locals);
            }
            BlockItem::Expr(expr) => collect_expr_wasm_locals(expr, locals),
        }
    }
}

fn collect_expr_wasm_locals(expr: &Expr, locals: &mut Vec<String>) {
    match expr {
        Expr::Call { args, .. } => {
            for arg in args {
                collect_expr_wasm_locals(arg, locals);
            }
        }
        Expr::MethodCall { receiver, args, .. } => {
            collect_expr_wasm_locals(receiver, locals);
            for arg in args {
                collect_expr_wasm_locals(arg, locals);
            }
        }
        Expr::FieldAccess { receiver, .. } => collect_expr_wasm_locals(receiver, locals),
        Expr::StructLiteral { value, .. } => collect_expr_wasm_locals(value, locals),
        Expr::Binary { left, right, .. } => {
            collect_expr_wasm_locals(left, locals);
            collect_expr_wasm_locals(right, locals);
        }
        Expr::Match {
            scrutinee, arms, ..
        } => {
            collect_expr_wasm_locals(scrutinee, locals);
            for arm in arms {
                collect_pattern_wasm_locals(&arm.pattern, locals);
                collect_expr_wasm_locals(&arm.expr, locals);
            }
        }
        Expr::Lambda { body, .. } => collect_expr_wasm_locals(body, locals),
        Expr::Block(block, _) => collect_block_wasm_locals(block, locals),
        Expr::Int(_, _)
        | Expr::Bool(_, _)
        | Expr::String(_, _)
        | Expr::Unit(_)
        | Expr::Var(_, _) => {}
    }
}

fn collect_pattern_wasm_locals(pattern: &Pattern, locals: &mut Vec<String>) {
    match pattern {
        Pattern::Var(name) => {
            if !locals.contains(name) {
                locals.push(name.clone());
            }
        }
        Pattern::Variant {
            payload: Some(payload),
            ..
        } => collect_pattern_wasm_locals(payload, locals),
        Pattern::Int(_)
        | Pattern::Bool(_)
        | Pattern::Unit
        | Pattern::Wildcard
        | Pattern::Variant { payload: None, .. } => {}
    }
}

fn wasm_result_type(annotation: &Option<Type>, program: &Program) -> &'static str {
    match annotation {
        Some(Type::Named(name)) if is_enum_type(name, program) => "i64",
        Some(Type::Apply { name, .. }) if is_enum_type(name, program) => "i64",
        _ => "i32",
    }
}

fn is_enum_type(name: &str, program: &Program) -> bool {
    if builtin_enum_names().iter().any(|builtin| *builtin == name) {
        return true;
    }
    program.items.iter().any(|item| {
        let TopLevelItem::Enum(decl) = item else {
            return false;
        };
        decl.name == name
    })
}

fn builtin_enum_names() -> &'static [&'static str] {
    &["Result", "PlatformError"]
}

fn expression_natural_type(expr: &Expr, program: &Program) -> &'static str {
    match expr {
        Expr::Var(name, _) => {
            if program.items.iter().any(|item| {
                let TopLevelItem::Enum(decl) = item else {
                    return false;
                };
                decl.variants.iter().any(|v| v.name == *name)
            }) || builtin_variant_tag(name).is_some()
            {
                "i64"
            } else {
                "i32"
            }
        }
        Expr::Call { name, .. } => {
            if program.items.iter().any(|item| {
                let TopLevelItem::Enum(decl) = item else {
                    return false;
                };
                decl.variants.iter().any(|v| v.name == *name)
            }) || builtin_variant_tag(name).is_some()
            {
                "i64"
            } else {
                let func = program.items.iter().find_map(|item| {
                    let TopLevelItem::Function(f) = item else {
                        return None;
                    };
                    if f.name == *name {
                        Some(f)
                    } else {
                        None
                    }
                });
                match func {
                    Some(f) => wasm_result_type(&f.return_annotation, program),
                    None => "i32",
                }
            }
        }
        Expr::Match { arms, .. } => arms
            .first()
            .map(|arm| expression_natural_type(&arm.expr, program))
            .unwrap_or("i32"),
        Expr::Block(block, _) => block
            .items
            .last()
            .map(|item| match item {
                BlockItem::Binding { expr, .. } => expression_natural_type(expr, program),
                BlockItem::Expr(expr) => expression_natural_type(expr, program),
            })
            .unwrap_or("i32"),
        _ => "i32",
    }
}

fn wat_line(out: &mut String, indent: usize, line: &str) {
    for _ in 0..indent {
        out.push_str("  ");
    }
    out.push_str(line);
    out.push('\n');
}

fn local_index(locals: &[String], name: &str) -> Result<usize> {
    locals
        .iter()
        .position(|local| local == name)
        .ok_or_else(|| {
            Error::new(format!(
                "internal wasm lowering error: unknown local `{name}`"
            ))
        })
}

fn wasi_glue_name(external_name: &str) -> String {
    match external_name {
        "_write_stdout_utf8!" => "emela_write_stdout_utf8".to_string(),
        "_write_stderr_utf8!" => "emela_write_stderr_utf8".to_string(),
        "_read_stdin_utf8!" => "emela_read_stdin_utf8".to_string(),
        "_now_i32!" => "emela_now_i32".to_string(),
        "_random_i32!" => "emela_random_i32".to_string(),
        "_read_file_utf8!" => "emela_read_file_utf8".to_string(),
        "_write_file_utf8!" => "emela_write_file_utf8".to_string(),
        "_get_env!" => "emela_get_env".to_string(),
        _ => external_name.to_string(),
    }
}

fn wasi_import_func_name(name: &str) -> String {
    format!("wasi_{name}")
}

fn wasi_import_sig(name: &str) -> (&'static str, &'static str) {
    match name {
        "fd_write" => ("(param i32 i32 i32 i32)", "(result i32)"),
        "fd_read" => ("(param i32 i32 i32 i32)", "(result i32)"),
        "clock_time_get" => ("(param i32 i64 i32)", "(result i32)"),
        "random_get" => ("(param i32 i32)", "(result i32)"),
        "path_open" => (
            "(param i32 i32 i32 i32 i32 i64 i64 i32 i32)",
            "(result i32)",
        ),
        "fd_close" => ("(param i32)", "(result i32)"),
        "environ_sizes_get" => ("(param i32 i32)", "(result i32)"),
        "environ_get" => ("(param i32 i32)", "(result i32)"),
        "proc_exit" => ("(param i32)", ""),
        _ => ("", ""),
    }
}

fn format_wasi_sig(params: &str, result: &str) -> String {
    format!("{params} {result}")
}

fn native_backend(target: Target) -> Result<&'static dyn NativeBackend> {
    match target.spec().backend {
        BackendKind::NativeAarch64Darwin => Ok(&AARCH64_DARWIN_BACKEND),
        BackendKind::NativeX86_64LinuxGnu => Ok(&X86_64_LINUX_GNU_BACKEND),
        BackendKind::None => Err(Error::new(format!(
            "target `{target}` does not have a native assembly backend yet"
        ))),
    }
}
