use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

use crate::ast::{BinaryOp, Block, BlockItem, Expr, Function, Pattern, Program};
use crate::error::{Error, Result};
use crate::platform::Target;
use crate::typecheck::TypedProgram;

pub(crate) fn emit_assembly(
    target: Target,
    program: &Program,
    typed: &TypedProgram,
) -> Result<String> {
    if !target.supports_native_backend() {
        return Err(Error::new(format!(
            "target `{target}` does not have a native assembly backend yet"
        )));
    }

    let types_by_name = typed
        .functions
        .iter()
        .map(|function| (function.name.as_str(), function))
        .collect::<HashMap<_, _>>();
    let comment = comment_marker(target);
    let mut out = String::new();
    out.push_str(comment);
    out.push_str(" Generated by the Emela compiler.\n");
    out.push_str(".text\n\n");

    for function in &program.functions {
        let typed_function = types_by_name[function.name.as_str()];
        if typed_function.effectful || !typed_function.capabilities.is_empty() {
            out.push_str(comment);
            out.push_str(" effects:");
            if typed_function.effectful {
                out.push_str(" effectful");
            }
            if !typed_function.capabilities.is_empty() {
                out.push_str(" requires ");
                out.push_str(
                    &typed_function
                        .capabilities
                        .iter()
                        .map(|capability| format!("{capability:?}"))
                        .collect::<Vec<_>>()
                        .join(","),
                );
            }
            out.push('\n');
        }
        out.push_str(&format!(
            "{comment} signature: ({}) -> {:?}\n",
            typed_function
                .params
                .iter()
                .map(|param| format!("{param:?}"))
                .collect::<Vec<_>>()
                .join(","),
            typed_function.ret
        ));

        let mut emitter = FunctionEmitter::new(target, function);
        emitter.emit_function(&mut out)?;
    }

    if target == Target::X86_64UnknownLinuxGnu {
        out.push_str(".section .note.GNU-stack,\"\",@progbits\n");
    }

    Ok(out)
}

pub(crate) fn build(target: Target, input: &Path, output: &Path, assembly: &str) -> Result<()> {
    if !target.supports_native_backend() {
        return Err(Error::new(format!(
            "target `{target}` does not have a native assembly backend yet"
        )));
    }
    if Target::host()? != target {
        return Err(Error::new(format!(
            "building target `{target}` requires running on a matching host; use --emit-asm for cross-target assembly output"
        )));
    }

    let temp = env::temp_dir().join(format!(
        "emela-{}-{}.s",
        std::process::id(),
        input.file_stem().and_then(|s| s.to_str()).unwrap_or("out")
    ));
    fs::write(&temp, assembly).map_err(|err| {
        Error::new(format!(
            "failed to write temporary assembly `{}`: {err}",
            temp.display()
        ))
    })?;

    let status = Command::new("cc")
        .arg(&temp)
        .arg("-o")
        .arg(output)
        .status()
        .map_err(|err| Error::new(format!("failed to execute cc: {err}")))?;

    let _ = fs::remove_file(&temp);

    if !status.success() {
        return Err(Error::new(format!(
            "cc failed while building `{}`",
            output.display()
        )));
    }
    Ok(())
}

struct FunctionEmitter<'a> {
    target: Target,
    function: &'a Function,
    label_prefix: String,
    locals: HashMap<String, i32>,
    next_label: usize,
}

impl<'a> FunctionEmitter<'a> {
    fn new(target: Target, function: &'a Function) -> Self {
        let mut locals = HashMap::new();
        let mut next_slot = 1;
        for param in &function.params {
            locals.insert(param.clone(), -4 * next_slot);
            next_slot += 1;
        }
        collect_block_bindings(&function.body, &mut locals, &mut next_slot);
        Self {
            target,
            function,
            label_prefix: sanitize_label(&symbol_name(target, &function.name)),
            locals,
            next_label: 0,
        }
    }

    fn emit_function(&mut self, out: &mut String) -> Result<()> {
        let symbol = if self.function.name == "main" || self.function.name == "main!" {
            main_symbol(self.target).to_string()
        } else {
            symbol_name(self.target, &self.function.name)
        };
        let frame_size = align_to(self.locals.len() as i32 * 4, 16);

        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str(".p2align 2\n");
                out.push_str(&format!(".globl {symbol}\n"));
                out.push_str(&format!("{symbol}:\n"));
                out.push_str("    stp x29, x30, [sp, #-16]!\n");
                out.push_str("    mov x29, sp\n");
                if frame_size > 0 {
                    out.push_str(&format!("    sub sp, sp, #{frame_size}\n"));
                }
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str(".p2align 4\n");
                out.push_str(&format!(".globl {symbol}\n"));
                out.push_str(&format!("{symbol}:\n"));
                out.push_str("    pushq %rbp\n");
                out.push_str("    movq %rsp, %rbp\n");
                if frame_size > 0 {
                    out.push_str(&format!("    subq ${frame_size}, %rsp\n"));
                }
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }

        for (index, param) in self.function.params.iter().enumerate() {
            if index >= 8 {
                return Err(Error::new(
                    "native backend supports at most 8 function parameters",
                ));
            }
            let offset = self.local_offset(param)?;
            match self.target {
                Target::Aarch64AppleDarwin => {
                    out.push_str(&format!("    str w{index}, [x29, #{offset}]\n"));
                }
                Target::X86_64UnknownLinuxGnu => {
                    const ARG_REGS: [&str; 6] = ["%edi", "%esi", "%edx", "%ecx", "%r8d", "%r9d"];
                    if let Some(reg) = ARG_REGS.get(index) {
                        out.push_str(&format!("    movl {reg}, {offset}(%rbp)\n"));
                    } else {
                        let stack_offset = 16 + (index - ARG_REGS.len()) * 8;
                        out.push_str(&format!("    movl {stack_offset}(%rbp), %eax\n"));
                        out.push_str(&format!("    movl %eax, {offset}(%rbp)\n"));
                    }
                }
                Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
            }
        }

        self.emit_block(&self.function.body, out)?;

        if self.function.name == "main" || self.function.name == "main!" {
            // main returns the process exit code in the target ABI result register.
            // Unit is represented as zero.
        }

        match self.target {
            Target::Aarch64AppleDarwin => {
                if frame_size > 0 {
                    out.push_str(&format!("    add sp, sp, #{frame_size}\n"));
                }
                out.push_str("    ldp x29, x30, [sp], #16\n");
                out.push_str("    ret\n\n");
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    leave\n");
                out.push_str("    ret\n\n");
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
        Ok(())
    }

    fn emit_block(&mut self, block: &Block, out: &mut String) -> Result<()> {
        if block.items.is_empty() {
            self.emit_i32(0, out);
            return Ok(());
        }

        let mut last_was_expr = false;
        for item in &block.items {
            match item {
                BlockItem::Binding { name, expr } => {
                    self.emit_expr(expr, out)?;
                    let offset = self.local_offset(name)?;
                    self.store_result(offset, out);
                    last_was_expr = false;
                }
                BlockItem::Expr(expr) => {
                    self.emit_expr(expr, out)?;
                    last_was_expr = true;
                }
            }
        }

        if !last_was_expr {
            self.emit_i32(0, out);
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, out: &mut String) -> Result<()> {
        match expr {
            Expr::Int(value) => {
                self.emit_i32(*value as u32, out);
            }
            Expr::Bool(value) => {
                self.emit_i32(if *value { 1 } else { 0 }, out);
            }
            Expr::Unit => self.emit_i32(0, out),
            Expr::Var(name) => {
                let offset = self.local_offset(name)?;
                match self.target {
                    Target::Aarch64AppleDarwin => {
                        out.push_str(&format!("    ldr w0, [x29, #{offset}]\n"));
                    }
                    Target::X86_64UnknownLinuxGnu => {
                        out.push_str(&format!("    movl {offset}(%rbp), %eax\n"));
                    }
                    Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
                }
            }
            Expr::Call { name, args } => self.emit_call(name, args, out)?,
            Expr::MethodCall {
                receiver,
                name,
                args,
            } => self.emit_method_call(receiver, name, args, out)?,
            Expr::Binary { op, left, right } => self.emit_binary(*op, left, right, out)?,
            Expr::Match { scrutinee, arms } => {
                let end_label = self.label("match_end");
                let mut arm_labels = Vec::new();
                let mut wildcard_label = None;

                self.emit_expr(scrutinee, out)?;
                self.push_result(out);

                for (index, arm) in arms.iter().enumerate() {
                    let label = self.label(&format!("match_arm_{index}"));
                    match &arm.pattern {
                        Pattern::Wildcard => wildcard_label = Some(label.clone()),
                        Pattern::Int(value) => {
                            self.emit_match_i32(*value as u32, &label, out);
                        }
                        Pattern::Bool(value) => {
                            self.emit_match_i32(if *value { 1 } else { 0 }, &label, out);
                        }
                        Pattern::Unit => {
                            self.emit_match_i32(0, &label, out);
                        }
                    }
                    arm_labels.push((label, &arm.expr));
                }

                if let Some(label) = &wildcard_label {
                    self.emit_jump(label, out);
                }

                for (label, arm_expr) in arm_labels {
                    out.push_str(&format!("{label}:\n"));
                    self.pop_match_value(out);
                    self.emit_expr(arm_expr, out)?;
                    self.emit_jump(&end_label, out);
                }

                out.push_str(&format!("{end_label}:\n"));
            }
            Expr::Block(block) => self.emit_block(block, out)?,
        }
        Ok(())
    }

    fn emit_call(&mut self, name: &str, args: &[Expr], out: &mut String) -> Result<()> {
        if args.len() > 8 {
            return Err(Error::new(
                "native backend supports at most 8 call arguments",
            ));
        }

        match self.target {
            Target::Aarch64AppleDarwin => {
                let stack_size = align_to(args.len() as i32 * 16, 16);
                if stack_size > 0 {
                    out.push_str(&format!("    sub sp, sp, #{stack_size}\n"));
                }
                for (index, arg) in args.iter().enumerate() {
                    self.emit_expr(arg, out)?;
                    out.push_str(&format!("    str w0, [sp, #{}]\n", index * 16));
                }
                for index in 0..args.len() {
                    out.push_str(&format!("    ldr w{index}, [sp, #{}]\n", index * 16));
                }
                if stack_size > 0 {
                    out.push_str(&format!("    add sp, sp, #{stack_size}\n"));
                }
                out.push_str(&format!("    bl {}\n", symbol_name(self.target, name)));
            }
            Target::X86_64UnknownLinuxGnu => {
                const ARG_REGS: [&str; 6] = ["%edi", "%esi", "%edx", "%ecx", "%r8d", "%r9d"];
                let stack_args = args.len().saturating_sub(ARG_REGS.len());
                let outgoing_size = stack_args * 8;
                let temp_offset = outgoing_size;
                let stack_size = align_to((outgoing_size + args.len() * 16) as i32, 16);
                if stack_size > 0 {
                    out.push_str(&format!("    subq ${stack_size}, %rsp\n"));
                }
                for (index, arg) in args.iter().enumerate() {
                    self.emit_expr(arg, out)?;
                    out.push_str(&format!(
                        "    movl %eax, {}(%rsp)\n",
                        temp_offset + index * 16
                    ));
                }
                for (index, reg) in ARG_REGS.iter().enumerate().take(args.len()) {
                    out.push_str(&format!(
                        "    movl {}(%rsp), {reg}\n",
                        temp_offset + index * 16
                    ));
                }
                for index in ARG_REGS.len()..args.len() {
                    out.push_str(&format!(
                        "    movl {}(%rsp), %eax\n",
                        temp_offset + index * 16
                    ));
                    out.push_str(&format!(
                        "    movl %eax, {}(%rsp)\n",
                        (index - ARG_REGS.len()) * 8
                    ));
                }
                out.push_str(&format!("    call {}\n", symbol_name(self.target, name)));
                if stack_size > 0 {
                    out.push_str(&format!("    addq ${stack_size}, %rsp\n"));
                }
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
        Ok(())
    }

    fn emit_method_call(
        &mut self,
        receiver: &Expr,
        name: &str,
        args: &[Expr],
        out: &mut String,
    ) -> Result<()> {
        if args.len() != 1 {
            return Err(Error::new(format!(
                "native backend only supports unary primitive method `{name}`"
            )));
        }
        self.emit_binary(method_op(name)?, receiver, &args[0], out)
    }

    fn emit_binary(
        &mut self,
        op: BinaryOp,
        left: &Expr,
        right: &Expr,
        out: &mut String,
    ) -> Result<()> {
        self.emit_expr(left, out)?;
        self.push_result(out);
        self.emit_expr(right, out)?;
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str("    ldr w9, [sp], #16\n");
                match op {
                    BinaryOp::Add => out.push_str("    add w0, w9, w0\n"),
                    BinaryOp::Sub => out.push_str("    sub w0, w9, w0\n"),
                    BinaryOp::Mul => out.push_str("    mul w0, w9, w0\n"),
                    BinaryOp::Eq => {
                        out.push_str("    cmp w9, w0\n");
                        out.push_str("    cset w0, eq\n");
                    }
                    BinaryOp::Lt => {
                        out.push_str("    cmp w9, w0\n");
                        out.push_str("    cset w0, lt\n");
                    }
                }
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    movl (%rsp), %r9d\n");
                out.push_str("    addq $16, %rsp\n");
                match op {
                    BinaryOp::Add => out.push_str("    addl %r9d, %eax\n"),
                    BinaryOp::Sub => {
                        out.push_str("    subl %eax, %r9d\n");
                        out.push_str("    movl %r9d, %eax\n");
                    }
                    BinaryOp::Mul => out.push_str("    imull %r9d, %eax\n"),
                    BinaryOp::Eq => {
                        out.push_str("    cmpl %eax, %r9d\n");
                        out.push_str("    sete %al\n");
                        out.push_str("    movzbl %al, %eax\n");
                    }
                    BinaryOp::Lt => {
                        out.push_str("    cmpl %eax, %r9d\n");
                        out.push_str("    setl %al\n");
                        out.push_str("    movzbl %al, %eax\n");
                    }
                }
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
        Ok(())
    }

    fn emit_i32(&self, value: u32, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str(&format!("    mov w0, #{value}\n")),
            Target::X86_64UnknownLinuxGnu => out.push_str(&format!("    movl ${value}, %eax\n")),
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn store_result(&self, offset: i32, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str(&format!("    str w0, [x29, #{offset}]\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str(&format!("    movl %eax, {offset}(%rbp)\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn push_result(&self, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str("    str w0, [sp, #-16]!\n"),
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    subq $16, %rsp\n");
                out.push_str("    movl %eax, (%rsp)\n");
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn pop_match_value(&self, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str("    add sp, sp, #16\n"),
            Target::X86_64UnknownLinuxGnu => out.push_str("    addq $16, %rsp\n"),
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn emit_match_i32(&self, value: u32, label: &str, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str("    ldr w9, [sp]\n");
                out.push_str(&format!("    mov w10, #{value}\n"));
                out.push_str("    cmp w9, w10\n");
                out.push_str(&format!("    b.eq {label}\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str(&format!("    cmpl ${value}, (%rsp)\n"));
                out.push_str(&format!("    je {label}\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn emit_jump(&self, label: &str, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str(&format!("    b {label}\n")),
            Target::X86_64UnknownLinuxGnu => out.push_str(&format!("    jmp {label}\n")),
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn local_offset(&self, name: &str) -> Result<i32> {
        self.locals
            .get(name)
            .copied()
            .ok_or_else(|| Error::new(format!("internal codegen error: unknown local `{name}`")))
    }

    fn label(&mut self, prefix: &str) -> String {
        let label = format!("L_{}_{}_{}", self.label_prefix, prefix, self.next_label);
        self.next_label += 1;
        label
    }
}

fn collect_block_bindings(block: &Block, locals: &mut HashMap<String, i32>, next_slot: &mut i32) {
    for item in &block.items {
        match item {
            BlockItem::Binding { name, expr } => {
                locals.entry(name.clone()).or_insert_with(|| {
                    let offset = -4 * *next_slot;
                    *next_slot += 1;
                    offset
                });
                collect_expr_bindings(expr, locals, next_slot);
            }
            BlockItem::Expr(expr) => collect_expr_bindings(expr, locals, next_slot),
        }
    }
}

fn collect_expr_bindings(expr: &Expr, locals: &mut HashMap<String, i32>, next_slot: &mut i32) {
    match expr {
        Expr::Call { args, .. } => {
            for arg in args {
                collect_expr_bindings(arg, locals, next_slot);
            }
        }
        Expr::MethodCall { receiver, args, .. } => {
            collect_expr_bindings(receiver, locals, next_slot);
            for arg in args {
                collect_expr_bindings(arg, locals, next_slot);
            }
        }
        Expr::Binary { left, right, .. } => {
            collect_expr_bindings(left, locals, next_slot);
            collect_expr_bindings(right, locals, next_slot);
        }
        Expr::Match { scrutinee, arms } => {
            collect_expr_bindings(scrutinee, locals, next_slot);
            for arm in arms {
                collect_expr_bindings(&arm.expr, locals, next_slot);
            }
        }
        Expr::Block(block) => collect_block_bindings(block, locals, next_slot),
        Expr::Int(_) | Expr::Bool(_) | Expr::Unit | Expr::Var(_) => {}
    }
}

fn method_op(name: &str) -> Result<BinaryOp> {
    match name {
        "add" => Ok(BinaryOp::Add),
        "sub" => Ok(BinaryOp::Sub),
        "mul" => Ok(BinaryOp::Mul),
        "eq" => Ok(BinaryOp::Eq),
        "lt" => Ok(BinaryOp::Lt),
        _ => Err(Error::new(format!(
            "native backend does not support method `{name}`"
        ))),
    }
}

fn main_symbol(target: Target) -> &'static str {
    match target {
        Target::Aarch64AppleDarwin => "_main",
        Target::X86_64UnknownLinuxGnu => "main",
        Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
    }
}

fn comment_marker(target: Target) -> &'static str {
    match target {
        Target::Aarch64AppleDarwin => "//",
        Target::X86_64UnknownLinuxGnu => "#",
        Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
    }
}

fn symbol_name(target: Target, name: &str) -> String {
    let base = name
        .strip_suffix('!')
        .map(|base| format!("{base}_effect"))
        .unwrap_or_else(|| name.to_string());
    match target {
        Target::Aarch64AppleDarwin => format!("_{base}"),
        Target::X86_64UnknownLinuxGnu => base,
        Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
    }
}

fn sanitize_label(value: &str) -> String {
    value
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect()
}

fn align_to(value: i32, align: i32) -> i32 {
    if value == 0 {
        0
    } else {
        ((value + align - 1) / align) * align
    }
}
