use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

use crate::ast::{BinaryOp, Block, BlockItem, Expr, Function, Pattern, Program, TopLevelItem};
use crate::error::{Error, Result};
use crate::external::{self, ExternalFunction, ExternalImplementation};
use crate::platform::{BackendKind, LinkerKind, Target};
use crate::typecheck::TypedProgram;

trait NativeBackend {
    fn comment_marker(&self) -> &'static str;
    fn main_symbol(&self) -> &'static str;
    fn symbol_name(&self, name: &str) -> String;
    fn stack_note(&self) -> Option<&'static str> {
        None
    }
}

struct Aarch64DarwinBackend;
struct X86_64LinuxGnuBackend;

impl NativeBackend for Aarch64DarwinBackend {
    fn comment_marker(&self) -> &'static str {
        "//"
    }

    fn main_symbol(&self) -> &'static str {
        "_main"
    }

    fn symbol_name(&self, name: &str) -> String {
        format!("_{}", base_symbol_name(name))
    }
}

impl NativeBackend for X86_64LinuxGnuBackend {
    fn comment_marker(&self) -> &'static str {
        "#"
    }

    fn main_symbol(&self) -> &'static str {
        "main"
    }

    fn symbol_name(&self, name: &str) -> String {
        base_symbol_name(name)
    }

    fn stack_note(&self) -> Option<&'static str> {
        Some(".section .note.GNU-stack,\"\",@progbits\n")
    }
}

static AARCH64_DARWIN_BACKEND: Aarch64DarwinBackend = Aarch64DarwinBackend;
static X86_64_LINUX_GNU_BACKEND: X86_64LinuxGnuBackend = X86_64LinuxGnuBackend;

pub(crate) fn emit_assembly(
    target: Target,
    program: &Program,
    typed: &TypedProgram,
) -> Result<String> {
    if !target.supports_native_backend() {
        return Err(Error::new(format!(
            "target `{target}` does not have a native assembly backend yet"
        )));
    }
    let backend = native_backend(target)?;

    let types_by_name = typed
        .functions
        .iter()
        .map(|function| (function.name.as_str(), function))
        .collect::<HashMap<_, _>>();
    let comment = backend.comment_marker();
    let mut out = String::new();
    out.push_str(comment);
    out.push_str(" Generated by the Emela compiler.\n");
    out.push_str(".text\n\n");

    for function in program.functions() {
        let typed_function = types_by_name[function.name.as_str()];
        if typed_function.effectful || !typed_function.capabilities.is_empty() {
            out.push_str(comment);
            out.push_str(" effects:");
            if typed_function.effectful {
                out.push_str(" effectful");
            }
            if !typed_function.capabilities.is_empty() {
                out.push_str(" requires ");
                out.push_str(
                    &typed_function
                        .capabilities
                        .iter()
                        .map(|capability| format!("{capability:?}"))
                        .collect::<Vec<_>>()
                        .join(","),
                );
            }
            out.push('\n');
        }
        out.push_str(&format!(
            "{comment} signature: ({}) -> {:?}\n",
            typed_function
                .params
                .iter()
                .map(|param| format!("{param:?}"))
                .collect::<Vec<_>>()
                .join(","),
            typed_function.ret
        ));

        let mut emitter = FunctionEmitter::new(target, backend, function, program);
        emitter.emit_function(&mut out)?;
    }

    if let Some(note) = backend.stack_note() {
        out.push_str(note);
    }

    Ok(out)
}

pub(crate) fn build(target: Target, input: &Path, output: &Path, assembly: &str) -> Result<()> {
    if !target.supports_native_backend() {
        return Err(Error::new(format!(
            "target `{target}` does not have a native assembly backend yet"
        )));
    }
    if target.spec().linker != LinkerKind::HostCc {
        return Err(Error::new(format!(
            "target `{target}` does not have a host cc linker configuration"
        )));
    }
    if Target::host()? != target {
        return Err(Error::new(format!(
            "building target `{target}` requires running on a matching host; use --emit-asm for cross-target assembly output"
        )));
    }

    let temp = env::temp_dir().join(format!(
        "emela-{}-{}.s",
        std::process::id(),
        input.file_stem().and_then(|s| s.to_str()).unwrap_or("out")
    ));
    fs::write(&temp, assembly).map_err(|err| {
        Error::new(format!(
            "failed to write temporary assembly `{}`: {err}",
            temp.display()
        ))
    })?;

    let status = Command::new("cc")
        .arg(&temp)
        .arg("-o")
        .arg(output)
        .status()
        .map_err(|err| Error::new(format!("failed to execute cc: {err}")))?;

    let _ = fs::remove_file(&temp);

    if !status.success() {
        return Err(Error::new(format!(
            "cc failed while building `{}`",
            output.display()
        )));
    }
    Ok(())
}

struct FunctionEmitter<'a> {
    target: Target,
    backend: &'static dyn NativeBackend,
    function: &'a Function,
    program: &'a Program,
    label_prefix: String,
    locals: HashMap<String, i32>,
    next_label: usize,
}

impl<'a> FunctionEmitter<'a> {
    fn new(
        target: Target,
        backend: &'static dyn NativeBackend,
        function: &'a Function,
        program: &'a Program,
    ) -> Self {
        let mut locals = HashMap::new();
        let mut next_slot = 1;
        for param in &function.params {
            locals.insert(param.name.clone(), -8 * next_slot);
            next_slot += 1;
        }
        collect_block_bindings(&function.body, &mut locals, &mut next_slot);
        Self {
            target,
            backend,
            function,
            program,
            label_prefix: sanitize_label(&backend.symbol_name(&function.name)),
            locals,
            next_label: 0,
        }
    }

    fn emit_function(&mut self, out: &mut String) -> Result<()> {
        let symbol = if self.function.name == "main" || self.function.name == "main!" {
            self.backend.main_symbol().to_string()
        } else {
            self.backend.symbol_name(&self.function.name)
        };
        let frame_size = align_to(self.locals.len() as i32 * 8, 16);

        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str(".p2align 2\n");
                out.push_str(&format!(".globl {symbol}\n"));
                out.push_str(&format!("{symbol}:\n"));
                out.push_str("    stp x29, x30, [sp, #-16]!\n");
                out.push_str("    mov x29, sp\n");
                if frame_size > 0 {
                    out.push_str(&format!("    sub sp, sp, #{frame_size}\n"));
                }
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str(".p2align 4\n");
                out.push_str(&format!(".globl {symbol}\n"));
                out.push_str(&format!("{symbol}:\n"));
                out.push_str("    pushq %rbp\n");
                out.push_str("    movq %rsp, %rbp\n");
                if frame_size > 0 {
                    out.push_str(&format!("    subq ${frame_size}, %rsp\n"));
                }
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }

        for (index, param) in self.function.params.iter().enumerate() {
            if index >= 8 {
                return Err(Error::new(
                    "native backend supports at most 8 function parameters",
                ));
            }
            let offset = self.local_offset(&param.name)?;
            match self.target {
                Target::Aarch64AppleDarwin => {
                    out.push_str(&format!("    str x{index}, [x29, #{offset}]\n"));
                }
                Target::X86_64UnknownLinuxGnu => {
                    const ARG_REGS: [&str; 6] = ["%rdi", "%rsi", "%rdx", "%rcx", "%r8", "%r9"];
                    if let Some(reg) = ARG_REGS.get(index) {
                        out.push_str(&format!("    movq {reg}, {offset}(%rbp)\n"));
                    } else {
                        let stack_offset = 16 + (index - ARG_REGS.len()) * 8;
                        out.push_str(&format!("    movq {stack_offset}(%rbp), %rax\n"));
                        out.push_str(&format!("    movq %rax, {offset}(%rbp)\n"));
                    }
                }
                Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
            }
        }

        self.emit_block(&self.function.body, out)?;

        if self.function.name == "main" || self.function.name == "main!" {
            // main returns the process exit code in the target ABI result register.
            // Unit is represented as zero.
        }

        match self.target {
            Target::Aarch64AppleDarwin => {
                if frame_size > 0 {
                    out.push_str(&format!("    add sp, sp, #{frame_size}\n"));
                }
                out.push_str("    ldp x29, x30, [sp], #16\n");
                out.push_str("    ret\n\n");
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    leave\n");
                out.push_str("    ret\n\n");
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
        Ok(())
    }

    fn emit_block(&mut self, block: &Block, out: &mut String) -> Result<()> {
        if block.items.is_empty() {
            self.emit_i32(0, out);
            return Ok(());
        }

        let mut last_was_expr = false;
        for item in &block.items {
            match item {
                BlockItem::Binding { name, expr, .. } => {
                    self.emit_expr(expr, out)?;
                    let offset = self.local_offset(name)?;
                    self.store_result(offset, out);
                    last_was_expr = false;
                }
                BlockItem::Expr(expr) => {
                    self.emit_expr(expr, out)?;
                    last_was_expr = true;
                }
            }
        }

        if !last_was_expr {
            self.emit_i32(0, out);
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, out: &mut String) -> Result<()> {
        match expr {
            Expr::Int(value) => {
                self.emit_i32(*value as u32, out);
            }
            Expr::Bool(value) => {
                self.emit_i32(if *value { 1 } else { 0 }, out);
            }
            Expr::Unit => self.emit_i32(0, out),
            Expr::Var(name) => {
                if let Some(tag) = self.find_variant_tag(name) {
                    self.emit_i32(tag as u32, out);
                    return Ok(());
                }
                if self.find_program_function(name) || self.find_external_function(name).is_some() {
                    return Err(Error::new(format!(
                        "native backend does not support function value `{name}` yet"
                    )));
                }
                let offset = self.local_offset(name)?;
                match self.target {
                    Target::Aarch64AppleDarwin => {
                        out.push_str(&format!("    ldr x0, [x29, #{offset}]\n"));
                    }
                    Target::X86_64UnknownLinuxGnu => {
                        out.push_str(&format!("    movq {offset}(%rbp), %rax\n"));
                    }
                    Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
                }
            }
            Expr::Call { name, args } => self.emit_call(name, args, out)?,
            Expr::MethodCall {
                receiver,
                name,
                args,
            } => self.emit_method_call(receiver, name, args, out)?,
            Expr::FieldAccess { receiver, .. } => self.emit_expr(receiver, out)?,
            Expr::StructLiteral { value, .. } => self.emit_expr(value, out)?,
            Expr::Binary { op, left, right } => self.emit_binary(*op, left, right, out)?,
            Expr::Match { scrutinee, arms } => {
                let end_label = self.label("match_end");
                let mut arm_labels = Vec::new();
                let mut wildcard_label = None;

                self.emit_expr(scrutinee, out)?;
                self.push_result(out);

                for (index, arm) in arms.iter().enumerate() {
                    let label = self.label(&format!("match_arm_{index}"));
                    match &arm.pattern {
                        Pattern::Wildcard => wildcard_label = Some(label.clone()),
                        Pattern::Var(_) => wildcard_label = Some(label.clone()),
                        Pattern::Int(value) => {
                            self.emit_match_i32(*value as u32, &label, out);
                        }
                        Pattern::Bool(value) => {
                            self.emit_match_i32(if *value { 1 } else { 0 }, &label, out);
                        }
                        Pattern::Unit => {
                            self.emit_match_i32(0, &label, out);
                        }
                        Pattern::Variant { name, .. } => {
                            let tag = self.variant_tag(name)? as u32;
                            self.emit_match_tag(tag, &label, out);
                        }
                    }
                    arm_labels.push((label, &arm.pattern, &arm.expr));
                }

                if let Some(label) = &wildcard_label {
                    self.emit_jump(label, out);
                }

                for (label, pattern, arm_expr) in arm_labels {
                    out.push_str(&format!("{label}:\n"));
                    self.bind_pattern_payload(pattern, out)?;
                    self.pop_match_value(out);
                    self.emit_expr(arm_expr, out)?;
                    self.emit_jump(&end_label, out);
                }

                out.push_str(&format!("{end_label}:\n"));
            }
            Expr::Block(block) => self.emit_block(block, out)?,
        }
        Ok(())
    }

    fn emit_call(&mut self, name: &str, args: &[Expr], out: &mut String) -> Result<()> {
        if let Some(tag) = self.find_variant_tag(name) {
            if args.len() != 1 {
                return Err(Error::new(format!(
                    "native backend expects enum variant `{name}` to have one payload"
                )));
            }
            self.emit_expr(&args[0], out)?;
            self.pack_enum(tag as u32, out);
            return Ok(());
        }

        if let Some(function) = self.find_external_function(name) {
            let implementation = match function.implementation {
                ExternalImplementation::Runtime => "runtime",
            };
            return Err(Error::new(format!(
                "external {implementation} function `{}` from `{}` does not have native lowering for target `{}` yet",
                function.name,
                format_external_path(function),
                self.target
            )));
        }

        if !self.find_program_function(name) {
            return Err(Error::new(format!(
                "native backend does not support calling function value `{name}` yet"
            )));
        }

        if args.len() > 8 {
            return Err(Error::new(
                "native backend supports at most 8 call arguments",
            ));
        }

        match self.target {
            Target::Aarch64AppleDarwin => {
                let stack_size = align_to(args.len() as i32 * 16, 16);
                if stack_size > 0 {
                    out.push_str(&format!("    sub sp, sp, #{stack_size}\n"));
                }
                for (index, arg) in args.iter().enumerate() {
                    self.emit_expr(arg, out)?;
                    out.push_str(&format!("    str x0, [sp, #{}]\n", index * 16));
                }
                for index in 0..args.len() {
                    out.push_str(&format!("    ldr x{index}, [sp, #{}]\n", index * 16));
                }
                if stack_size > 0 {
                    out.push_str(&format!("    add sp, sp, #{stack_size}\n"));
                }
                out.push_str(&format!("    bl {}\n", self.backend.symbol_name(name)));
            }
            Target::X86_64UnknownLinuxGnu => {
                const ARG_REGS: [&str; 6] = ["%rdi", "%rsi", "%rdx", "%rcx", "%r8", "%r9"];
                let stack_args = args.len().saturating_sub(ARG_REGS.len());
                let outgoing_size = stack_args * 8;
                let temp_offset = outgoing_size;
                let stack_size = align_to((outgoing_size + args.len() * 16) as i32, 16);
                if stack_size > 0 {
                    out.push_str(&format!("    subq ${stack_size}, %rsp\n"));
                }
                for (index, arg) in args.iter().enumerate() {
                    self.emit_expr(arg, out)?;
                    out.push_str(&format!(
                        "    movq %rax, {}(%rsp)\n",
                        temp_offset + index * 16
                    ));
                }
                for (index, reg) in ARG_REGS.iter().enumerate().take(args.len()) {
                    out.push_str(&format!(
                        "    movq {}(%rsp), {reg}\n",
                        temp_offset + index * 16
                    ));
                }
                for index in ARG_REGS.len()..args.len() {
                    out.push_str(&format!(
                        "    movq {}(%rsp), %rax\n",
                        temp_offset + index * 16
                    ));
                    out.push_str(&format!(
                        "    movq %rax, {}(%rsp)\n",
                        (index - ARG_REGS.len()) * 8
                    ));
                }
                out.push_str(&format!("    call {}\n", self.backend.symbol_name(name)));
                if stack_size > 0 {
                    out.push_str(&format!("    addq ${stack_size}, %rsp\n"));
                }
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
        Ok(())
    }

    fn emit_method_call(
        &mut self,
        receiver: &Expr,
        name: &str,
        args: &[Expr],
        out: &mut String,
    ) -> Result<()> {
        if args.len() != 1 {
            return Err(Error::new(format!(
                "native backend only supports unary primitive method `{name}`"
            )));
        }
        self.emit_binary(method_op(name)?, receiver, &args[0], out)
    }

    fn emit_binary(
        &mut self,
        op: BinaryOp,
        left: &Expr,
        right: &Expr,
        out: &mut String,
    ) -> Result<()> {
        self.emit_expr(left, out)?;
        self.push_result(out);
        self.emit_expr(right, out)?;
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str("    ldr w9, [sp], #16\n");
                match op {
                    BinaryOp::Add => out.push_str("    add w0, w9, w0\n"),
                    BinaryOp::Sub => out.push_str("    sub w0, w9, w0\n"),
                    BinaryOp::Mul => out.push_str("    mul w0, w9, w0\n"),
                    BinaryOp::Eq => {
                        out.push_str("    cmp w9, w0\n");
                        out.push_str("    cset w0, eq\n");
                    }
                    BinaryOp::Lt => {
                        out.push_str("    cmp w9, w0\n");
                        out.push_str("    cset w0, lt\n");
                    }
                }
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    movl (%rsp), %r9d\n");
                out.push_str("    addq $16, %rsp\n");
                match op {
                    BinaryOp::Add => out.push_str("    addl %r9d, %eax\n"),
                    BinaryOp::Sub => {
                        out.push_str("    subl %eax, %r9d\n");
                        out.push_str("    movl %r9d, %eax\n");
                    }
                    BinaryOp::Mul => out.push_str("    imull %r9d, %eax\n"),
                    BinaryOp::Eq => {
                        out.push_str("    cmpl %eax, %r9d\n");
                        out.push_str("    sete %al\n");
                        out.push_str("    movzbl %al, %eax\n");
                    }
                    BinaryOp::Lt => {
                        out.push_str("    cmpl %eax, %r9d\n");
                        out.push_str("    setl %al\n");
                        out.push_str("    movzbl %al, %eax\n");
                    }
                }
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
        Ok(())
    }

    fn emit_i32(&self, value: u32, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str(&format!("    mov w0, #{value}\n")),
            Target::X86_64UnknownLinuxGnu => out.push_str(&format!("    movl ${value}, %eax\n")),
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn pack_enum(&self, tag: u32, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str("    lsl x0, x0, #32\n");
                out.push_str(&format!("    orr x0, x0, #{tag}\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    shlq $32, %rax\n");
                out.push_str(&format!("    orq ${tag}, %rax\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn store_result(&self, offset: i32, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str(&format!("    str x0, [x29, #{offset}]\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str(&format!("    movq %rax, {offset}(%rbp)\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn push_result(&self, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str("    str x0, [sp, #-16]!\n"),
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    subq $16, %rsp\n");
                out.push_str("    movq %rax, (%rsp)\n");
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn pop_match_value(&self, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str("    add sp, sp, #16\n"),
            Target::X86_64UnknownLinuxGnu => out.push_str("    addq $16, %rsp\n"),
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn emit_match_i32(&self, value: u32, label: &str, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str("    ldr w9, [sp]\n");
                out.push_str(&format!("    mov w10, #{value}\n"));
                out.push_str("    cmp w9, w10\n");
                out.push_str(&format!("    b.eq {label}\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str(&format!("    cmpl ${value}, (%rsp)\n"));
                out.push_str(&format!("    je {label}\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn emit_match_tag(&self, tag: u32, label: &str, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => {
                out.push_str("    ldr x9, [sp]\n");
                out.push_str("    and x9, x9, #0xffffffff\n");
                out.push_str(&format!("    cmp x9, #{tag}\n"));
                out.push_str(&format!("    b.eq {label}\n"));
            }
            Target::X86_64UnknownLinuxGnu => {
                out.push_str("    movq (%rsp), %r9\n");
                out.push_str("    andq $4294967295, %r9\n");
                out.push_str(&format!("    cmpq ${tag}, %r9\n"));
                out.push_str(&format!("    je {label}\n"));
            }
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn emit_jump(&self, label: &str, out: &mut String) {
        match self.target {
            Target::Aarch64AppleDarwin => out.push_str(&format!("    b {label}\n")),
            Target::X86_64UnknownLinuxGnu => out.push_str(&format!("    jmp {label}\n")),
            Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
        }
    }

    fn local_offset(&self, name: &str) -> Result<i32> {
        self.locals
            .get(name)
            .copied()
            .ok_or_else(|| Error::new(format!("internal codegen error: unknown local `{name}`")))
    }

    fn bind_pattern_payload(&self, pattern: &Pattern, out: &mut String) -> Result<()> {
        match pattern {
            Pattern::Variant {
                payload: Some(payload),
                ..
            } => self.bind_pattern_payload_value(payload, true, out),
            Pattern::Var(name) => {
                let offset = self.local_offset(name)?;
                match self.target {
                    Target::Aarch64AppleDarwin => {
                        out.push_str("    ldr x9, [sp]\n");
                        out.push_str(&format!("    str x9, [x29, #{offset}]\n"));
                    }
                    Target::X86_64UnknownLinuxGnu => {
                        out.push_str("    movq (%rsp), %r9\n");
                        out.push_str(&format!("    movq %r9, {offset}(%rbp)\n"));
                    }
                    Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
                }
                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn bind_pattern_payload_value(
        &self,
        pattern: &Pattern,
        unpack_enum: bool,
        out: &mut String,
    ) -> Result<()> {
        match pattern {
            Pattern::Var(name) => {
                let offset = self.local_offset(name)?;
                match self.target {
                    Target::Aarch64AppleDarwin => {
                        out.push_str("    ldr x9, [sp]\n");
                        if unpack_enum {
                            out.push_str("    lsr x9, x9, #32\n");
                        }
                        out.push_str(&format!("    str x9, [x29, #{offset}]\n"));
                    }
                    Target::X86_64UnknownLinuxGnu => {
                        out.push_str("    movq (%rsp), %r9\n");
                        if unpack_enum {
                            out.push_str("    shrq $32, %r9\n");
                        }
                        out.push_str(&format!("    movq %r9, {offset}(%rbp)\n"));
                    }
                    Target::Wasm32UnknownUnknown | Target::Wasm32Wasi => unreachable!(),
                }
                Ok(())
            }
            Pattern::Wildcard | Pattern::Int(_) | Pattern::Bool(_) | Pattern::Unit => Ok(()),
            Pattern::Variant { payload, .. } => {
                if let Some(payload) = payload {
                    self.bind_pattern_payload_value(payload, true, out)
                } else {
                    Ok(())
                }
            }
        }
    }

    fn label(&mut self, prefix: &str) -> String {
        let label = format!("L_{}_{}_{}", self.label_prefix, prefix, self.next_label);
        self.next_label += 1;
        label
    }

    fn variant_tag(&self, name: &str) -> Result<usize> {
        self.find_variant_tag(name)
            .ok_or_else(|| Error::new(format!("internal codegen error: unknown variant `{name}`")))
    }

    fn find_variant_tag(&self, name: &str) -> Option<usize> {
        self.program.items.iter().find_map(|item| {
            let TopLevelItem::Enum(decl) = item else {
                return None;
            };
            decl.variants
                .iter()
                .position(|variant| variant.name == name)
        })
    }

    fn find_external_function(&self, name: &str) -> Option<&'static ExternalFunction> {
        self.program.items.iter().find_map(|item| {
            let TopLevelItem::Import(import) = item else {
                return None;
            };
            if import.name == name {
                external::resolve_import(&import.path, &import.name)
            } else {
                None
            }
        })
    }

    fn find_program_function(&self, name: &str) -> bool {
        self.program
            .functions()
            .iter()
            .any(|function| function.name == name)
    }
}

fn collect_block_bindings(block: &Block, locals: &mut HashMap<String, i32>, next_slot: &mut i32) {
    for item in &block.items {
        match item {
            BlockItem::Binding { name, expr, .. } => {
                locals.entry(name.clone()).or_insert_with(|| {
                    let offset = -8 * *next_slot;
                    *next_slot += 1;
                    offset
                });
                collect_expr_bindings(expr, locals, next_slot);
            }
            BlockItem::Expr(expr) => collect_expr_bindings(expr, locals, next_slot),
        }
    }
}

fn collect_expr_bindings(expr: &Expr, locals: &mut HashMap<String, i32>, next_slot: &mut i32) {
    match expr {
        Expr::Call { args, .. } => {
            for arg in args {
                collect_expr_bindings(arg, locals, next_slot);
            }
        }
        Expr::MethodCall { receiver, args, .. } => {
            collect_expr_bindings(receiver, locals, next_slot);
            for arg in args {
                collect_expr_bindings(arg, locals, next_slot);
            }
        }
        Expr::FieldAccess { receiver, .. } => collect_expr_bindings(receiver, locals, next_slot),
        Expr::StructLiteral { value, .. } => collect_expr_bindings(value, locals, next_slot),
        Expr::Binary { left, right, .. } => {
            collect_expr_bindings(left, locals, next_slot);
            collect_expr_bindings(right, locals, next_slot);
        }
        Expr::Match { scrutinee, arms } => {
            collect_expr_bindings(scrutinee, locals, next_slot);
            for arm in arms {
                collect_pattern_bindings(&arm.pattern, locals, next_slot);
                collect_expr_bindings(&arm.expr, locals, next_slot);
            }
        }
        Expr::Block(block) => collect_block_bindings(block, locals, next_slot),
        Expr::Int(_) | Expr::Bool(_) | Expr::Unit | Expr::Var(_) => {}
    }
}

fn collect_pattern_bindings(
    pattern: &Pattern,
    locals: &mut HashMap<String, i32>,
    next_slot: &mut i32,
) {
    match pattern {
        Pattern::Var(name) => {
            locals.entry(name.clone()).or_insert_with(|| {
                let offset = -8 * *next_slot;
                *next_slot += 1;
                offset
            });
        }
        Pattern::Variant {
            payload: Some(payload),
            ..
        } => collect_pattern_bindings(payload, locals, next_slot),
        Pattern::Int(_)
        | Pattern::Bool(_)
        | Pattern::Unit
        | Pattern::Wildcard
        | Pattern::Variant { payload: None, .. } => {}
    }
}

fn method_op(name: &str) -> Result<BinaryOp> {
    match name {
        "add" => Ok(BinaryOp::Add),
        "sub" => Ok(BinaryOp::Sub),
        "mul" => Ok(BinaryOp::Mul),
        "eq" => Ok(BinaryOp::Eq),
        "lt" => Ok(BinaryOp::Lt),
        _ => Err(Error::new(format!(
            "native backend does not support method `{name}`"
        ))),
    }
}

fn base_symbol_name(name: &str) -> String {
    name.strip_suffix('!')
        .map(|base| format!("{base}_effect"))
        .unwrap_or_else(|| name.to_string())
}

fn sanitize_label(value: &str) -> String {
    value
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect()
}

fn align_to(value: i32, align: i32) -> i32 {
    if value == 0 {
        0
    } else {
        ((value + align - 1) / align) * align
    }
}

fn format_external_path(function: &ExternalFunction) -> String {
    let mut parts = function.path.to_vec();
    parts.push(function.name);
    parts.join(".")
}

fn native_backend(target: Target) -> Result<&'static dyn NativeBackend> {
    match target.spec().backend {
        BackendKind::NativeAarch64Darwin => Ok(&AARCH64_DARWIN_BACKEND),
        BackendKind::NativeX86_64LinuxGnu => Ok(&X86_64_LINUX_GNU_BACKEND),
        BackendKind::None => Err(Error::new(format!(
            "target `{target}` does not have a native assembly backend yet"
        ))),
    }
}
