use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

use crate::ast::{BinaryOp, Block, BlockItem, Expr, Function, Pattern, Program};
use crate::error::{Error, Result};
use crate::platform::Target;
use crate::typecheck::TypedProgram;

pub(crate) fn emit_assembly(
    target: Target,
    program: &Program,
    typed: &TypedProgram,
) -> Result<String> {
    if !target.supports_native_backend() {
        return Err(Error::new(format!(
            "target `{target}` does not have a native assembly backend yet"
        )));
    }
    if std::env::consts::ARCH != "aarch64" {
        return Err(Error::new(format!(
            "native assembly backend only supports aarch64, got {}",
            std::env::consts::ARCH
        )));
    }

    let types_by_name = typed
        .functions
        .iter()
        .map(|function| (function.name.as_str(), function))
        .collect::<HashMap<_, _>>();
    let mut out = String::new();
    out.push_str("// Generated by the Emela compiler.\n");
    out.push_str(".text\n\n");

    for function in &program.functions {
        let typed_function = types_by_name[function.name.as_str()];
        if typed_function.effectful || !typed_function.capabilities.is_empty() {
            out.push_str("// effects:");
            if typed_function.effectful {
                out.push_str(" effectful");
            }
            if !typed_function.capabilities.is_empty() {
                out.push_str(" requires ");
                out.push_str(
                    &typed_function
                        .capabilities
                        .iter()
                        .map(|capability| format!("{capability:?}"))
                        .collect::<Vec<_>>()
                        .join(","),
                );
            }
            out.push('\n');
        }
        out.push_str(&format!(
            "// signature: ({}) -> {:?}\n",
            typed_function
                .params
                .iter()
                .map(|param| format!("{param:?}"))
                .collect::<Vec<_>>()
                .join(","),
            typed_function.ret
        ));

        let mut emitter = FunctionEmitter::new(function);
        emitter.emit_function(&mut out)?;
    }

    Ok(out)
}

pub(crate) fn build(target: Target, input: &Path, output: &Path, assembly: &str) -> Result<()> {
    if !target.supports_native_backend() {
        return Err(Error::new(format!(
            "target `{target}` does not have a native assembly backend yet"
        )));
    }

    let temp = env::temp_dir().join(format!(
        "emela-{}-{}.s",
        std::process::id(),
        input.file_stem().and_then(|s| s.to_str()).unwrap_or("out")
    ));
    fs::write(&temp, assembly).map_err(|err| {
        Error::new(format!(
            "failed to write temporary assembly `{}`: {err}",
            temp.display()
        ))
    })?;

    let status = Command::new("cc")
        .arg(&temp)
        .arg("-o")
        .arg(output)
        .status()
        .map_err(|err| Error::new(format!("failed to execute cc: {err}")))?;

    let _ = fs::remove_file(&temp);

    if !status.success() {
        return Err(Error::new(format!(
            "cc failed while building `{}`",
            output.display()
        )));
    }
    Ok(())
}

struct FunctionEmitter<'a> {
    function: &'a Function,
    label_prefix: String,
    locals: HashMap<String, i32>,
    next_label: usize,
}

impl<'a> FunctionEmitter<'a> {
    fn new(function: &'a Function) -> Self {
        let mut locals = HashMap::new();
        let mut next_slot = 1;
        for param in &function.params {
            locals.insert(param.clone(), -4 * next_slot);
            next_slot += 1;
        }
        collect_block_bindings(&function.body, &mut locals, &mut next_slot);
        Self {
            function,
            label_prefix: sanitize_label(&symbol_name(&function.name)),
            locals,
            next_label: 0,
        }
    }

    fn emit_function(&mut self, out: &mut String) -> Result<()> {
        let symbol = if self.function.name == "main" || self.function.name == "main!" {
            "_main".to_string()
        } else {
            symbol_name(&self.function.name)
        };
        let frame_size = align_to(self.locals.len() as i32 * 4, 16);

        out.push_str(".p2align 2\n");
        out.push_str(&format!(".globl {symbol}\n"));
        out.push_str(&format!("{symbol}:\n"));
        out.push_str("    stp x29, x30, [sp, #-16]!\n");
        out.push_str("    mov x29, sp\n");
        if frame_size > 0 {
            out.push_str(&format!("    sub sp, sp, #{frame_size}\n"));
        }

        for (index, param) in self.function.params.iter().enumerate() {
            if index >= 8 {
                return Err(Error::new(
                    "native backend supports at most 8 function parameters",
                ));
            }
            let offset = self.local_offset(param)?;
            out.push_str(&format!("    str w{index}, [x29, #{offset}]\n"));
        }

        self.emit_block(&self.function.body, out)?;

        if self.function.name == "main" || self.function.name == "main!" {
            // main returns the process exit code in w0. Unit is represented as zero.
        }

        if frame_size > 0 {
            out.push_str(&format!("    add sp, sp, #{frame_size}\n"));
        }
        out.push_str("    ldp x29, x30, [sp], #16\n");
        out.push_str("    ret\n\n");
        Ok(())
    }

    fn emit_block(&mut self, block: &Block, out: &mut String) -> Result<()> {
        if block.items.is_empty() {
            out.push_str("    mov w0, #0\n");
            return Ok(());
        }

        let mut last_was_expr = false;
        for item in &block.items {
            match item {
                BlockItem::Binding { name, expr } => {
                    self.emit_expr(expr, out)?;
                    let offset = self.local_offset(name)?;
                    out.push_str(&format!("    str w0, [x29, #{offset}]\n"));
                    last_was_expr = false;
                }
                BlockItem::Expr(expr) => {
                    self.emit_expr(expr, out)?;
                    last_was_expr = true;
                }
            }
        }

        if !last_was_expr {
            out.push_str("    mov w0, #0\n");
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, out: &mut String) -> Result<()> {
        match expr {
            Expr::Int(value) => {
                out.push_str(&format!("    mov w0, #{}\n", *value as u32));
            }
            Expr::Bool(value) => {
                out.push_str(&format!("    mov w0, #{}\n", if *value { 1 } else { 0 }));
            }
            Expr::Unit => out.push_str("    mov w0, #0\n"),
            Expr::Var(name) => {
                let offset = self.local_offset(name)?;
                out.push_str(&format!("    ldr w0, [x29, #{offset}]\n"));
            }
            Expr::Call { name, args } => self.emit_call(name, args, out)?,
            Expr::MethodCall {
                receiver,
                name,
                args,
            } => self.emit_method_call(receiver, name, args, out)?,
            Expr::Binary { op, left, right } => self.emit_binary(*op, left, right, out)?,
            Expr::Match { scrutinee, arms } => {
                let end_label = self.label("match_end");
                let mut arm_labels = Vec::new();
                let mut wildcard_label = None;

                self.emit_expr(scrutinee, out)?;
                out.push_str("    str w0, [sp, #-16]!\n");

                for (index, arm) in arms.iter().enumerate() {
                    let label = self.label(&format!("match_arm_{index}"));
                    match &arm.pattern {
                        Pattern::Wildcard => wildcard_label = Some(label.clone()),
                        Pattern::Int(value) => {
                            out.push_str("    ldr w9, [sp]\n");
                            out.push_str(&format!("    mov w10, #{}\n", *value as u32));
                            out.push_str("    cmp w9, w10\n");
                            out.push_str(&format!("    b.eq {label}\n"));
                        }
                        Pattern::Bool(value) => {
                            out.push_str("    ldr w9, [sp]\n");
                            out.push_str(&format!("    cmp w9, #{}\n", if *value { 1 } else { 0 }));
                            out.push_str(&format!("    b.eq {label}\n"));
                        }
                        Pattern::Unit => {
                            out.push_str("    ldr w9, [sp]\n");
                            out.push_str("    cmp w9, #0\n");
                            out.push_str(&format!("    b.eq {label}\n"));
                        }
                    }
                    arm_labels.push((label, &arm.expr));
                }

                if let Some(label) = &wildcard_label {
                    out.push_str(&format!("    b {label}\n"));
                }

                for (label, arm_expr) in arm_labels {
                    out.push_str(&format!("{label}:\n"));
                    out.push_str("    add sp, sp, #16\n");
                    self.emit_expr(arm_expr, out)?;
                    out.push_str(&format!("    b {end_label}\n"));
                }

                out.push_str(&format!("{end_label}:\n"));
            }
            Expr::Block(block) => self.emit_block(block, out)?,
        }
        Ok(())
    }

    fn emit_call(&mut self, name: &str, args: &[Expr], out: &mut String) -> Result<()> {
        if args.len() > 8 {
            return Err(Error::new(
                "native backend supports at most 8 call arguments",
            ));
        }

        let stack_size = align_to(args.len() as i32 * 16, 16);
        if stack_size > 0 {
            out.push_str(&format!("    sub sp, sp, #{stack_size}\n"));
        }
        for (index, arg) in args.iter().enumerate() {
            self.emit_expr(arg, out)?;
            out.push_str(&format!("    str w0, [sp, #{}]\n", index * 16));
        }
        for index in 0..args.len() {
            out.push_str(&format!("    ldr w{index}, [sp, #{}]\n", index * 16));
        }
        if stack_size > 0 {
            out.push_str(&format!("    add sp, sp, #{stack_size}\n"));
        }
        out.push_str(&format!("    bl {}\n", symbol_name(name)));
        Ok(())
    }

    fn emit_method_call(
        &mut self,
        receiver: &Expr,
        name: &str,
        args: &[Expr],
        out: &mut String,
    ) -> Result<()> {
        if args.len() != 1 {
            return Err(Error::new(format!(
                "native backend only supports unary primitive method `{name}`"
            )));
        }
        self.emit_binary(method_op(name)?, receiver, &args[0], out)
    }

    fn emit_binary(
        &mut self,
        op: BinaryOp,
        left: &Expr,
        right: &Expr,
        out: &mut String,
    ) -> Result<()> {
        self.emit_expr(left, out)?;
        out.push_str("    str w0, [sp, #-16]!\n");
        self.emit_expr(right, out)?;
        out.push_str("    ldr w9, [sp], #16\n");
        match op {
            BinaryOp::Add => out.push_str("    add w0, w9, w0\n"),
            BinaryOp::Sub => out.push_str("    sub w0, w9, w0\n"),
            BinaryOp::Mul => out.push_str("    mul w0, w9, w0\n"),
            BinaryOp::Eq => {
                out.push_str("    cmp w9, w0\n");
                out.push_str("    cset w0, eq\n");
            }
            BinaryOp::Lt => {
                out.push_str("    cmp w9, w0\n");
                out.push_str("    cset w0, lt\n");
            }
        }
        Ok(())
    }

    fn local_offset(&self, name: &str) -> Result<i32> {
        self.locals
            .get(name)
            .copied()
            .ok_or_else(|| Error::new(format!("internal codegen error: unknown local `{name}`")))
    }

    fn label(&mut self, prefix: &str) -> String {
        let label = format!("L_{}_{}_{}", self.label_prefix, prefix, self.next_label);
        self.next_label += 1;
        label
    }
}

fn collect_block_bindings(block: &Block, locals: &mut HashMap<String, i32>, next_slot: &mut i32) {
    for item in &block.items {
        match item {
            BlockItem::Binding { name, expr } => {
                locals.entry(name.clone()).or_insert_with(|| {
                    let offset = -4 * *next_slot;
                    *next_slot += 1;
                    offset
                });
                collect_expr_bindings(expr, locals, next_slot);
            }
            BlockItem::Expr(expr) => collect_expr_bindings(expr, locals, next_slot),
        }
    }
}

fn collect_expr_bindings(expr: &Expr, locals: &mut HashMap<String, i32>, next_slot: &mut i32) {
    match expr {
        Expr::Call { args, .. } => {
            for arg in args {
                collect_expr_bindings(arg, locals, next_slot);
            }
        }
        Expr::MethodCall { receiver, args, .. } => {
            collect_expr_bindings(receiver, locals, next_slot);
            for arg in args {
                collect_expr_bindings(arg, locals, next_slot);
            }
        }
        Expr::Binary { left, right, .. } => {
            collect_expr_bindings(left, locals, next_slot);
            collect_expr_bindings(right, locals, next_slot);
        }
        Expr::Match { scrutinee, arms } => {
            collect_expr_bindings(scrutinee, locals, next_slot);
            for arm in arms {
                collect_expr_bindings(&arm.expr, locals, next_slot);
            }
        }
        Expr::Block(block) => collect_block_bindings(block, locals, next_slot),
        Expr::Int(_) | Expr::Bool(_) | Expr::Unit | Expr::Var(_) => {}
    }
}

fn method_op(name: &str) -> Result<BinaryOp> {
    match name {
        "add" => Ok(BinaryOp::Add),
        "sub" => Ok(BinaryOp::Sub),
        "mul" => Ok(BinaryOp::Mul),
        "eq" => Ok(BinaryOp::Eq),
        "lt" => Ok(BinaryOp::Lt),
        _ => Err(Error::new(format!(
            "native backend does not support method `{name}`"
        ))),
    }
}

fn symbol_name(name: &str) -> String {
    let base = name
        .strip_suffix('!')
        .map(|base| format!("{base}_effect"))
        .unwrap_or_else(|| name.to_string());
    format!("_{}", base)
}

fn sanitize_label(value: &str) -> String {
    value
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect()
}

fn align_to(value: i32, align: i32) -> i32 {
    if value == 0 {
        0
    } else {
        ((value + align - 1) / align) * align
    }
}
